### ISSUE TITLE
Weapon components are not synced

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv-issues#280] opened 2019-09-19 16:38 UTC
When I set explosive rounds for weapons it doesn't get synched for others. It doesn't matter if I set it on client or on server side.

**For example:**
player.giveWeapon(0xA914799, 30, true);
player.addWeaponComponent(0xA914799, 0x89EBDAA7);

**Comment by Lekenthun** [comment] 2019-11-17 21:30
The problem here is that if I make the player immortal on client-side using setPlayerInvincible then the explosions created by this player (f.e.: component or grenade) are not synced.

**Comment by C0kkie** [comment] 2020-12-06 00:54
Should be fixed, we cant reproduce it anymore

**Closed** 2020-12-06 00:57 UTC
Labels: Class: bug, Scope: module-api, Side: server, Status: fixed
