### ISSUE TITLE
Server side bodyHealth setter on vehicle entity does not work

### ISSUE THREAD

**Issue by mexyn** [altmp/altv-issues#618] opened 2020-08-18 02:27 UTC
**Client/server version**

`Build #1285, branch rc`

**Current behavior**

The bodyHealth setter of the vehicle class does not work. Any value set is ignored. See here: https://streamable.com/gcqvxh
Code used to verify in the ingame console:

````alt.log(`Before setter: ${player.vehicle.bodyHealth}`);````
`player.vehicle.bodyHealth = 500;`
````alt.log(`After setter: ${player.vehicle.bodyHealth}`);````

The second log statement should give '500' as result, but always returns '1000'.

**Expected behavior**

bodyHealth value should be set properly to the passed value.

**Steps to reproduce**

See code example above and --> https://streamable.com/gcqvxh

**Context (environment)**

We use this property (and engineHealth) to track and set the health status of vehicles depending on saved health values in our database. E.g. when a player spawns a vehicle the bodyHealth should be set to the saved value of our database. Right now we cant do this, because the setter doesnt work. 

**Possible solution**

Make it work as intended :)

**Comment by tastydev** [comment] 2020-08-18 02:55
Can confirm, the property is also not in sync with the native get method if u have set it on clientside through the native.
Found #463 which got reported 5 months ago and flaged with false scope. It is not csharp-module related

**Comment by Lhoerion** [comment] 2020-08-18 12:25
Related to #463, thanks for pointing that out @tastydev
I'll keep both as they show reproduction steps for different properties

**Comment by tastydev** [comment] 2020-10-24 17:37
I found out that the setter does not work until the car got damaged once.
Example: 
1. spawn car 
2. set bodyhealth result: won´t work
3. damage the car by driving against or wall or something else
4. set bodyhealth result: works

**Comment by r3sist3nt** [comment] 2020-11-01 13:28
Works as intended now. This was fixed in **dev/2.1-dev5**.
Can someone assign the label fixed?

**Comment by Lhoerion** [comment] 2020-11-01 13:50
~~Added~~/Fixed/~~Changed~~ in build #[2.1-dev5](https://discord.com/channels/371265202378899476/528297438348574741/772440936293859328)

**Closed by Lhoerion** 2020-11-01 13:50 UTC
Labels: Class: bug, Scope: module-api, Side: server, Status: confirmed
