### ISSUE TITLE
Kuruma tuning bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1757] opened 2023-02-01 16:24 UTC
### Description of the problem

Since the last alt:V or GTA update, the vehmods.bin is severely incomplete, making server-side tunings not possible on some vehicles.

### Reproduction steps

Let's spawn a kuruma for example, and try to set the paintjob or turbo on it.

### Expected behaviour

-

### Operating system

Windows 11

### Version

alt:V build #13.44, branch release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment] 2023-02-01 16:25
duplicate of #1051 #1619

**Closed by FabianTerhorst** 2023-02-01 16:25 UTC
Labels: Class: bug
