### ISSUE TITLE
Server config

### ISSUE THREAD

**Issue by gruperpro93** [altmp/altv-issues#1035] opened 2021-07-27 02:43 UTC
**Suggestion**: add new parameter - alt.config

**Use cases** alt.config will display the server settings, for example, the maximum number of participants

**Comment by DurtyFree** [comment] 2021-07-28 11:31
@gruperpro93 Please edit your suggestion to fit our template: https://github.com/altmp/altv-issues/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by LeonMrBonnie** [comment] 2021-09-02 19:34
Duplicate of #197

**Closed by LeonMrBonnie** 2021-09-02 19:34 UTC
Labels: Class: enhancement
