### ISSUE TITLE
Quick quit clientside function API

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1566] opened 2022-07-19 10:15 UTC
### Description of the problem

There is currently no user-friendly way to quickly quit the game (console quit command doesn't count).

### Desired solution for the problem

Add quit function api to clientside.

### Alternatives you considered

Slow alternative: [native.restartGame](https://natives.altv.mp/#/0xE574A662ACAEFBB1)

### Version

11.0

**Comment by deluvas1911** [comment] 2022-07-19 10:16
duplicate of #1557

**Comment by xxshady** [comment] 2022-07-19 10:16
@deluvas1911 its not a duplicate, read **Desired solution for the problem** please

**Closed by deluvas1911** 2022-07-19 10:16 UTC
Labels: Status: duplicate, Class: enhancement

**Comment by FabianTerhorst** [comment] 2022-07-19 10:18
we won't add a api for closing the game.

**Comment by Lennart-1337** [comment] 2022-07-19 13:34
use native.restartGame()
