### ISSUE TITLE
Render WebView on Prop Texture broken @dev233

### ISSUE THREAD

**Issue by GVMP** [altmp/altv-issues#1869] opened 2023-06-11 12:09 UTC
### Description of the problem

The texture gets replaced, but it's just empty/black.

Switched to release branch and it works fine.

### Reproduction steps

const webview = new alt.WebView('http://resource/client/webview/index.html', propHash, 'screen_1');

### Expected behaviour

Render WebView on Texture

### Operating system

Windows

### Version

dev233

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment] 2023-06-11 14:37
it works for me on dev233

https://github.com/altmp/altv-issues/assets/54737754/cace49f5-a862-48c3-9ceb-a4ec1e0306da

**Comment by xxshady** [comment] 2023-06-11 14:55
Confirmed on 15.0-dev233, only happens with `useSharedTextures = true`

**Comment by C0kkie** [comment] 2023-07-26 13:03
Should be fixed in newest dev, if not reopen the issue

**Closed by C0kkie** 2023-07-26 13:03 UTC
Labels: Class: bug, Status: confirmed
