### ISSUE TITLE
Player invisible sometimes after setting into a vehicle (C# Serverside)

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1397] opened 2022-03-02 17:06 UTC
### Description of the problem

Sometimes after creating a vehicle and setting the player into it, the player is invisible and can't drive. The only way to be visible again and be able to drive is to press `F` to leave the vehicle and enter it again by yourself

### Reproduction steps

1. Spawn a vehicle and set the player into it using the serverside methode

### Expected behaviour

The player shouldn't be invisible and be able to drive

### Additional context

It only occurs sometimes

### Operating system

Windows 10 & Debian 10

### Version

release 9.6

**Comment by FabianTerhorst** [comment] 2022-03-02 17:07
Duplicate of #1174

**Closed by FabianTerhorst** 2022-03-02 17:07 UTC
Labels: Class: bug
