### ISSUE TITLE
Performance browser

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#559] opened 2020-05-29 21:39 UTC
Hi,
A performance-checking function/app would be neccesary. 
It would check the memory usage and CPU% of the given resource on client and on server side. 
(F.e.: snycedMeta, events, etc.) 
On MTA it worked very well and helped debugging. 
Link: https://wiki.multitheftauto.com/wiki/Resource:Performancebrowser

**Comment by danilaplee** [comment] 2020-08-16 19:29
for browser you can use chrome:devtools and for node you can as well use it.
But would love to see a debug port on the v8 client

**Comment by LeonMrBonnie** [comment] 2020-12-18 23:36
This can be achieved with the v8 Inspector protocol, so this is a duplicate of #652

**Closed by LeonMrBonnie** 2020-12-18 23:36 UTC
Labels: Class: enhancement, Scope: module-api, Side: client, Side: server
