### ISSUE TITLE
alt:V watermark causes black screen spinner text to be unreadable 

### ISSUE THREAD

**Issue by Firjens** [altmp/altv-issues#803] opened 2021-01-12 16:21 UTC
The alt:V watermark that is visible on any alt:V causes the text below the watermark to be unreadable. The text that is attached to the spinner should say "Authenticating".

![image](https://user-images.githubusercontent.com/57008952/104341493-28eb5280-54fa-11eb-9ae5-742633d24166.png)

Possible fixes for this problem is removing the watermark all together, making the watermark not visible when text is shown at that location, allowing the server to disable the watermark, making the watermark way more transparent, or changing the location of the watermark.

**Comment by LeonMrBonnie** [comment] 2021-01-12 16:22
Duplicate of https://github.com/altmp/altv-issues/issues/307

**Closed by LeonMrBonnie** 2021-01-12 16:22 UTC
Labels: Class: bug
