### ISSUE TITLE
Vehmods not working properly

### ISSUE THREAD

**Issue by Avepy** [altmp/altv-issues#2216] opened 2024-01-24 14:35 UTC
### Description of the problem

since the alt:V 16
before update car tuning looked like this with 7 1 - hood, 10 3 - roof:

![obraz_2024-01-24_153004010](https://github.com/altmp/altv-issues/assets/54192195/a2cb00cc-8502-4a79-94b8-e6a4f44b8420)

And now it looks like this with the same values:

![obraz_2024-01-24_153028939](https://github.com/altmp/altv-issues/assets/54192195/f9b3b201-a774-425d-aa1b-da66dab54eb8)

Car model: "tenf", but it happens to another vehicles too
I'm setting it now by serverside C#: 
```
vehicle.SetMod((byte) modType, (byte) variant);
```
but I've tried with clientside as well:
```
alt.on('consoleCommand', (command, ...args) => {
    if (command !== 'tuning') return;
    setVehicleMod(alt.Player.local.vehicle, parseInt(args[0]), parseInt(args[1]), false);
});
```
neither of these sets the correct modifications

### Reproduction steps

Try to set ModType of vehicles

### Expected behaviour

SetMod on server and client setting proper things
For example that's how roof nr. 3 looks like in game files:

![obraz_2024-01-24_163803953](https://github.com/altmp/altv-issues/assets/54192195/bc679715-5b61-4d1d-b5a8-6a3713d153a4)

So as on first screen, not like after update

### Operating system

Windows 11

### Version

release/16.0.51

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by toyerovsky** [comment] 2024-02-10 15:52
Hello, any update on that? @vadzz-dev

**Comment by ThomasMarangoni** [comment] 2024-02-11 08:46
Please don't tag our devs without real reason.

**Comment by Avepy** [comment] 2024-04-10 11:58
The issue still persists, I've noticed that clientside has to have set the modkit to 0 for setting mods, and serverside needs to have modkit 1 set.
Moreover, there's comparison between clientside and serverside tuning:

![image](https://github.com/altmp/altv-issues/assets/54192195/d8f8b39f-4e6f-4fe1-b277-4670f4012706)
Left one is the same tuning as the right one, but one on the left is set by clientside and one on the right by serverside.

Here's the code for serverside setting which I'm using
```
alt.onClient('createVehicle', (player: alt.Player, pos: alt.Vector3) => {
    const vehicle = new alt.Vehicle('tenf', pos.x, pos.y, pos.z, 0, 0, 0);
    vehicle.numberPlateText = 'TUNING';
    vehicle.engineOn = true;
    vehicle.modKit = 1;

    setTimeout(() => {
        vehicle.setMod(7, 1);
        vehicle.setMod(10, 3);
    }, 2500);
});
````
and here is clientside one
```
natives.setVehicleModKit(alt.Player.local.vehicle.scriptID, 0);
natives.setVehicleMod(alt.Player.local.vehicle, 7, 1, false);
natives.setVehicleMod(alt.Player.local.vehicle, 10, 3, false);
```

None of these tunings look like the ones from OpenIV

**Comment by banbu123** [comment] 2024-05-28 20:41
Hello, currently there is the problem that all tuning parts of the Vulcar Nebula Turbo are mixed up. 
Unfortunately it is not a server-side problem, but an “Alt:V problem”.

Something is wrong with the “tuning script” (if you call it that :D )

I would ask you to have a look at it, since the update in january the car has changed except for the paint job. 

there was the same problem with the sentinel classic widebody back then.

Unfortunately I don't have a before and after picture, I also tried it on the server PlayV and there is always an error message.

**Comment by banbu123** [comment] 2024-06-10 17:19
i found a old picture of "my" Nebula.

![nebula before](https://github.com/altmp/altv-issues/assets/85082902/1b54c527-1426-48db-9123-bc8b97827ae3)

and now it looks a little different  :*)

![GTA5 2024-06-10 19-17-22](https://github.com/altmp/altv-issues/assets/85082902/ccf767e7-381e-4d7c-b02e-62b69cfb08e4)

**Comment by ItsMeDeli** [comment] 2024-06-25 18:19
Anything known about this?

**Comment by ItsMeDeli** [comment] 2024-06-26 11:21
We noticed that the problem is less when all vehicles are merged into one resource. But still, it's not practical.

**Comment by toyerovsky** [comment] 2024-08-17 14:32
Problem with tenf has fixed on its own.

**Closed** 2024-08-17 15:02 UTC
Labels: Class: bug
