### ISSUE TITLE
Joining server with -debug argument updates altv.toml

### ISSUE THREAD

**Issue by MusaSSH** [altmp/altv-issues#1859] opened 2023-05-31 22:57 UTC
### Description of the problem

-debug mode sets debug to true in altv.toml

### Reproduction steps

- Open altv.toml and make sure debug is false.
- altv.exe -debug
- Join a debug mode enabled server (This step is important, this is where the problem happens.)
- Open altv.toml and check if debug is now true.

### Expected behaviour

debug setting in altv.toml shouldn't be updated from false to true when you run altv with -debug argument.

In #1500 I suggested this feature to be a fast switch between debug and production modes, but this bug makes it persistent between two alt:V instance.

### Additional context

If you run the game with -debug argument but do not join a server, it doesn't update altv.toml, so joining a debug server is where the bug actually occurs.

### Operating system

Windows

### Version

dev/15-dev203

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment] 2023-05-31 22:59
duplicate of #1806

**Closed by C0kkie** 2023-05-31 22:59 UTC
Labels: Class: bug
