### ISSUE TITLE
Trucks and trailers

### ISSUE THREAD

**Issue by MyliuDideliBusta** [altmp/altv-issues#492] opened 2020-03-26 21:16 UTC
We faced a bug with a Truck trailers, if there is 2 players close by trailer, trailer detaches automatically from truck which one has trailer attached,

**Comment by lameule123** [comment] 2020-08-09 18:48
I have also this bug wich is caused by netowner change i think.
Trailer are just unusable currently in my opinion.

**Comment by C0kkie** [comment] 2020-12-07 23:27
Got fixed in dev2.1/14

**Closed** 2020-12-07 23:28 UTC
Labels: Class: bug, Scope: native, Side: client, Status: to-investigate
