### ISSUE TITLE
Bulk Repair() within short timespan freezes server

### ISSUE THREAD

**Issue by DasNiels** [altmp/altv-issues#1078] opened 2021-08-29 07:33 UTC
**Client/server version**
Release 5.4

Tested on C# module!

**Current behavior**
Was a pain to figure out. But basically I tried respawning all unoccupied vehicles in my server. That froze my server. After trying several solutions given on the altv c# docs and from other members on the discord, deluvas1911 and I figured out that "Repair();" was causing it. On respawn it would repair the vehicle and thus after a random amount of vehicles it froze the server.

**Expected behavior**
Server shouldnt freeze.

**Steps to reproduce**
- Spawn eg 800 cars or so.
- preferably spawn it via an entity factory so you can save it's initial pos and rot.
- add a respawn method to your custom class that sets its position/rotation back to the original pos/rot AND repairs the vehicle.
- loop thru all vehicles and respawn them, either with a short Task.Delay or not. We discovered that with a long enough delay(1 vehicle per second...) it wouldnt freeze up.
- wait for the freeze

**Context (environment)**
I'd like to be able to respawn all (unoccupied) vehicles

**Possible solution**
No idea, but it's definitely related to Repair.

**Comment by Heryshaf** [comment] 2021-08-29 07:48
Duplicate of https://github.com/altmp/altv-issues/issues/787
It was added to the merge window to be fixed. along the fixing without netowner, but it didn't happen, yet.

**Comment by xxshady** [comment] 2021-08-29 07:53
@Heryshaf but there is nothing said about the server freeze

**Comment by xxshady** [comment] 2021-08-29 07:54
can confirm on js

**Comment by Heryshaf** [comment] 2021-08-29 07:54
Yeah we just discussed it internally, sadly, it was reported when the function was first introduced. :(

**Comment by DasNiels** [comment] 2021-08-29 07:58
Well, glad I'm atleast not the only one

**Comment by xxshady** [comment] 2021-08-29 08:01
It really was a big pain when I couldn't understand why we had this happening. Although it's already late, but thank you so much for discovering the reason for this

**Comment by C0kkie** [comment] 2021-09-13 11:49
Should be fixed in next dev

**Closed by C0kkie** 2021-09-13 11:49 UTC
Labels: Class: bug, Side: server, Status: confirmed, Scope: internal
