### ISSUE TITLE
SetLightDamage(byte lightId, bool IsDamaged) doesn't work properly

### ISSUE THREAD

**Issue by Kaiwoknats** [altmp/altv-issues#1438] opened 2022-04-16 16:13 UTC
### Description of the problem

I wrote a method which saves and loads vehicle damage from database on vehicle creation.

On some vehicles it works all fine but on the emperor it often doesn't apply the right lightdamage.

I tested it on other vehicles too and it does appear there as well.

### Reproduction steps
```cs
public void ApplyVehicleDamageData( ){


AltAsync.RunOnMainThread( ( ) =>
            {
                foreach ( var light in VehicleLightList ) // List of VehicleLightDamage
                {
                    SetLightDamaged( light.Id, light.IsDamaged );
                }
            } );


}

 public class VehicleLightDamage
    {
        public byte Id { get; set; }
        public bool IsDamaged { get; set; }
    }
```

### Expected behaviour

It would be nice if the setlightdamage would always apply the right value.

### Additional context

Video to demonstrate:

https://medal.tv/games/gta-v/clips/hZ1lmou-oeAbA/d1337OuaLJzs?invite=cr-MSx1ZGosMzM3OTQ2NjEs

### Operating system

Windows 10

### Version

dev/10.0.51

**Comment by xxshady** [comment] 2022-04-16 16:15
@Kaiwoknats duplicate of #737

**Closed** 2022-04-16 16:16 UTC
Labels: Class: bug
