### ISSUE TITLE
Vehicle health setter not working after repair

### ISSUE THREAD

**Issue by Konders** [altmp/altv-issues#1623] opened 2022-08-22 06:48 UTC
### Description of the problem

Repro code
```

const SET_FULL_HP = {
	[alt.hash("tr2")]: true,
	[alt.hash("trflat")]: true,
};

alt.on("vehicleDestroy", (veh) => {
	veh.repair();
	if (!SET_FULL_HP[veh.model])
		alt.setTimeout(() => {
			veh.engineHealth = 300;
			veh.bodyHealth = 300;
			alt.log("Veh health", veh.engineHealth, veh.bodyHealth);
		}, 1000);
});

```

### Reproduction steps

Destroy vehicle
Repair
Set engine/body health
output health getter
gotta default 1000 hp

### Expected behaviour

Destroy vehicle
Repair
Set engine/body health -> 300
output health getter
gotta 300 hp

### Operating system

Windows 11

### Version

12.10 (release)

**Comment by FabianTerhorst** [comment] 2022-08-22 07:11
Duplicate of #1184

**Closed** 2022-08-22 07:11 UTC
Labels: Class: bug
