### ISSUE TITLE
getForHandlingName errors

### ISSUE THREAD

**Issue by Konders** [altmp/altv-issues#1294] opened 2021-12-27 07:30 UTC
### Description of the problem

`[09:26:30][Error] [V8] Exception at core:client/systems/handling.js:87
[09:26:30][Error]       const handling = alt.HandlingData.getForHandlingName(vehicle.handling.handlingN...
[09:26:30][Error]   Error: Failed to convert argument 1 to uint32
    at client/systems/handling.js:87:36`

### Reproduction steps

`alt.on("enteredVehicle", (vehicle, seat) => {
	const handling = alt.HandlingData.getForHandlingName(vehicle.handling.handlingNameHash);
	alt.log(handling);
});`

/veh cheburek

### Expected behaviour

We successfully got handling data

### Additional context

With oracle everything works good, maybe this problem are model based and can be reproduced not only with cheburek

### Operating system

Windows 11

### Version

8.4 (release)

**Comment by Konders** [comment] 2021-12-27 08:53
buffalo4 affects too

**Comment by zziger** [comment] 2021-12-27 09:08
Happens for me on some dlc vehicles too

**Comment by xxshady** [comment] 2022-09-25 16:52
I can assume it was caused by a bug in the js module
https://github.com/altmp/altv-js-module/commit/cc61215cacfc8f2da210dfff690965197b54df2e

**Comment by xxshady** [comment] 2022-09-25 16:57
`handlingNameHash` on cheburek now returns the correct hash
![изображение](https://user-images.githubusercontent.com/54737754/192155580-66a52429-5c6c-4789-9d34-4d992fa5341a.png)

**Comment by xxshady** [comment] 2022-09-25 17:00
Dlc vehicles still seem to be broken
![изображение](https://user-images.githubusercontent.com/54737754/192155735-513033aa-946b-4c5f-b30e-44bd316b4981.png)

**Comment by xxshady** [comment] 2022-09-25 17:06
Can we maybe close this since we already have #1173?

**Comment by C0kkie** [comment] 2023-03-16 23:14
Yea we can close this one here as resolved then

**Closed by C0kkie** 2023-03-16 23:14 UTC
Labels: Class: bug, Status: confirmed
