### ISSUE TITLE
VirtualEntity data parameter bug

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#2158] opened 2023-12-23 04:10 UTC
### Description of the problem

If you set a new key to `VirtualEntity` with `setStreamSyncedMeta`, other keys which are set by the `VirtualEntity`'s last parameter (data) will invoke on client side `streamSyncedMetaChange` event.

Take a look at console log (`--- EXTRA INVOKE BEGINS HERE ---`) that I wrote in reproduction steps.
Maybe this problem comes from `js-module`.

### Reproduction steps

- Server side:
```js
import alt from 'alt-server';

const virtualEntityGroup = new alt.VirtualEntityGroup(128);
const player = alt.Player.getByID(1);
const data = {
    type: 'object',
    customData: [0, 1, 2, 3, 4]
};

const virtualEntity = new alt.VirtualEntity(
    virtualEntityGroup,
    new alt.Vector3(
        player.pos.x,
        player.pos.y,
        player.pos.z
    ),
    10,
    data
);

// --- Problem begins here ---
setTimeout(() => {
    virtualEntity.setStreamSyncedMeta('111', 'setTimeout 1');
}, 3000);
// --- Problem ends here ---

setTimeout(() => {
    virtualEntity.setStreamSyncedMeta('333333', 'setTimeout 2');
}, 6000);

setTimeout(() => {
    virtualEntity.setStreamSyncedMeta('333333', 'setTimeout 3');
}, 9000);
```
- Client side:
```js
import alt from 'alt-client';

alt.on('streamSyncedMetaChange', (entity, key, value, oldValue) => {
    alt.log('~r~streamSyncedMetaChange');
    alt.log(key + ' - ' + value + ' - ' + oldValue);
});
```
- Client console log:
```
--- EXTRA INVOKE BEGINS HERE ---
[04:44:09] streamSyncedMetaChange
[04:44:09] type - object - object
[04:44:09] streamSyncedMetaChange
[04:44:09] customData - 0,1,2,3,4 - 0,1,2,3,4
--- EXTRA INVOKE ENDS HERE ---

[04:44:09] streamSyncedMetaChange
[04:44:09] 111 - setTimeout 1 - undefined

[04:44:12] streamSyncedMetaChange
[04:44:12] 333333 - setTimeout 2 - undefined

[04:44:15] streamSyncedMetaChange
[04:44:15] 333333 - setTimeout 3 - setTimeout 2
```

### Expected behaviour

Should not invoke other keys.

### Operating system

Windows 10

### Version

dev/15.0-dev976

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by xxshady** [comment] 2023-12-23 07:42
duplicate of #1977

**Closed by xxshady** 2023-12-23 07:42 UTC
Labels: Class: bug
