### ISSUE TITLE
Crash on dev 353

### ISSUE THREAD

**Issue by Pixel220** [altmp/altv-issues#1905] opened 2023-07-13 13:45 UTC
### Description of the problem

If you get on any two-wheeled vehicle, you'll crash.
Tested on BMX, Bati, sanchez.

### Reproduction steps
If I set the id of a non-existing wheel to alt.Player.local.vehicle.getWheelSurfaceMaterial(id), it crashes
I spawned a two-wheeled vehicle, set it to
alt.Player.local.vehicle.getWheelSurfaceMaterial(2)
Got crash

### Expected behaviour

Normal driving

### Operating system

Windows 11 22H2

### Version

dev/353

### Crashdump ID

6039ce78-a866-4908-a32c-ea4c415d949e

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment] 2023-07-13 14:00
Can't reproduce on dev353
![изображение](https://github.com/altmp/altv-issues/assets/54737754/98f0c437-695d-485e-a15b-5018c4f05e51)

**Comment by xxshady** [comment] 2023-07-13 14:35
Should be fixed in next dev build

**Closed by xxshady** 2023-07-13 14:35 UTC
Labels: Class: bug, Status: confirmed
