### ISSUE TITLE
2D VoiceChannel doesnt work outside of the stream zone

### ISSUE THREAD

**Issue by vasreb** [altmp/altv-issues#646] opened 2020-09-12 17:29 UTC
**Client/server version**

`Build #1299, branch rc`

**Current behavior**

I create 2d voicechannel this way:

`new VoiceChannel(false, 0)`

Which should give me the behavior of an unlimited distance channel working at any distance for players who add to it.

But in fact, when the players move further from each other streamDistance, they stop hearing each other.

When `streamDistance: 9999` it works for the whole map. so the bug is clearly related to streamDistance

**Expected behavior**

Unlimited working range for 2D voicechannel (new VoiceChannel(false, 0))

**Steps to reproduce**

0. Download RC server with default resources
1. Add to the default chat resource below debug lines

```
const v = new alt.VoiceChannel(false, 0);
registerCmd("voice", (p) => v.addPlayer(p));
```

2. Join to the server
3. Type /voice with second guy
4. Speak to microphone (hear ok)
5. Go far
6. Speak to microphone (dont hear)

**Context (environment)**

Implement an phone call behavior via 2d VoiceChannel

**Possible solution**

Do unlimited stream range for 2d VoiceChannel entity

**Comment by MacieGx** [comment] 2020-09-14 20:31
Same issue.
If two players are out of stream range and on the same voice channel, they cannot hear each other, but the TX and RX increases when they speak.

**Comment by vadzz-dev** [comment] 2020-09-15 09:50
Was investigating that and found that it was caused by one of last updates. Would be fixed in near time

**Comment by emcifuntik** [comment] 2020-12-17 16:16
should be fixed

**Closed by emcifuntik** 2020-12-17 16:16 UTC
Labels: Class: bug, Scope: voice, Side: server, Status: confirmed
