### ISSUE TITLE
new F8 Console UI Issues (Double log lines not shown correct)

### ISSUE THREAD

**Issue by BluePeer** [altmp/altv-issues#2380] opened 2024-11-23 22:57 UTC
### Description of the problem

like you see on the first and second screen
there is a issue with the Ignore multiple lines and the display of the number infront

if you mostly (change arround the messages)
create log messages that are double
means like example trigger a static message on press a button
the first is shown
the second is not shown (missing (2) next to the message
3 in a row sometimes shown same for 4 and 5 but only sometimes
sometimes it shows on 4 oder 5 multiple but not in every case
and the before not shown count get added after some other log messages (but not all time only sometimes)
to trigger a correct count mostly you need to rerender the full view with add/remove timestamp

![image](https://github.com/user-attachments/assets/123df029-fd5b-42c6-b135-1868b6ea44e5)
if you change the timestamp, the view get a total different view
![image](https://github.com/user-attachments/assets/d865b938-a6b4-481d-920e-eed97db21c49)

and in some cases the UI response (f8 press) to open is +1 Second (mostly first time)
and scroll with mouse wheel is huge low FPS (looks like 5 fps)

### Reproduction steps

see above the examples

### Expected behaviour

show correct numbers on multiple identical lines in all cases

### Operating system

Windows

### Version

alt:V build #16.2.25-rc.5, branch rc

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by MellKam** [comment] 2024-11-24 10:18
This should be already fixed in the altv-ui repository, waiting for a new release to apply these fixes. Thanks for reporting it

**Comment by BluePeer** [comment] 2024-11-28 22:00
> This should be already fixed in the altv-ui repository, waiting for a new release to apply these fixes. Thanks for reporting it

i can confirm this for the most cases in
alt:V build 16.2.25-rc.13

but there is still a issue with multi display on for example error messages
it shows a X icon regular (not multicount) and if you use for example the timestamp flipper (on/off)
it switch from the icon to the multicount view (that get only update on flipp/rerender

![image](https://github.com/user-attachments/assets/0a7f9ab4-36c0-4e25-a9fb-8b4e00372a71)

**Comment by MellKam** [comment] 2024-11-29 09:22
@BluePeer Can you please provide some simple example how can I reproduce this behavior? Cause I didn't quite understand what I should do to cause this.

**Comment by BluePeer** [comment] 2024-11-29 09:25
start alt:V
press F8
enter "voiceVolume"

this creates the example used error message (repeait it 5 times) you will see only the X) press show time it switch to the at this time counter
use some additive "voiceVolume" no counter update reuse the switch, counter update

whatever triggers a alt.logError

**Comment by MellKam** [comment] 2024-11-29 13:26
@BluePeer I just tested the Release and RC client and it looks like my fixes have not been applied yet. I'll ask to update it as soon as possible

**Comment by MellKam** [comment] 2024-12-19 09:05
@BluePeer This issue should be resolved in the RC branch. Let me know if you still encounter it.

**Closed as completed** 2024-12-20 05:50 UTC
Labels: Class: bug
