### ISSUE TITLE
Boats like to drive themselves after 8.0 update

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1299] opened 2021-12-29 12:43 UTC
### Description of the problem

Since 8.0 update, boats tend to drive themselves around the ocean randomly.

No idea what triggers it (maybe it triggers when driver disconnects? or just really random). But this never happened before 8.0 update.

We have a heist on the server that uses a boat. Boat can be located via a command. Whenever the boat is missing, we locate it and fly(noclip) to the boat to find itself sailing around the ocean. Only way to stop it is to get it stuck somehow on eg shore.

### Reproduction steps

I don't have any, only speculation:

- Totally random
- When driver disconnects while sailing it.
- When driver dies while sailing it.

### Expected behaviour

Boat should behave and only move when instructed to :)

### Additional context

Tested with "squalo", although I assume it happens on other boats too.

Only fix I can think of right now is to turn engine off on player exit, and turn it on when player enters. And have engine turned off on spawn ofcourse.

### Operating system

Ubuntu 20.04 (server), Windows 10 (client)

### Version

Release 8.6

**Comment by YannBCF** [comment] 2021-12-29 12:47
This issue is known and it was already there before 8.0, it happens with atleast cars too as it could be reproduced on QA server on dev/9.0-dev1 build.

Easy reproduction step: kick a player driving.
Guessed technical cause: the vehicle task doesnt get cleared.

**Comment by CoffeeGen** [comment] 2021-12-29 12:49
> This issue is known and it was already there before 8.0, it happens with atleast cars too as it could be reproduced on QA server on dev/9.0-dev1 build.
> 
> Easy reproduction step: kick a player driving. Guessed technical cause: the vehicle task doesnt get cleared.

Ahh I see. Is that an easy fix to implement in 9.0? Or is there something we can do as server owners(eg clear task clientside if possible)?

**Comment by Stuyk** [comment] 2021-12-30 15:12
> > This issue is known and it was already there before 8.0, it happens with atleast cars too as it could be reproduced on QA server on dev/9.0-dev1 build.
> > Easy reproduction step: kick a player driving. Guessed technical cause: the vehicle task doesnt get cleared.
> 
> Ahh I see. Is that an easy fix to implement in 9.0? Or is there something we can do as server owners(eg clear task clientside if possible)?

Maybe before you kick a user you can try setting their position to their own position. This effectively kicks them out of the vehicle. Cannot confirm if this works but it may be a work around for now.

**Comment by FabianTerhorst** [comment] 2022-01-04 01:24
Duplicate of #362

**Closed by FabianTerhorst** 2022-01-04 01:24 UTC
Labels: Class: bug
