### ISSUE TITLE
Download issues with Resource Containerization feature

### ISSUE THREAD

**Issue by TheOutburst** [altmp/altv-issues#2374] opened 2024-11-21 21:48 UTC
### Description of the problem

Greetings,

we have tried the Resource containerization after the update and found 2 errors

Error 1:
With containerization switched on, various DLCs occasionally lead to instand crashes after restarts, which we have also had in live operation for months now and are otherwise not noticeable in either clientside or serverside logs. Including this free mod, for recreation purposes: https://www.gta5-mods.com/maps/tiny-secret-garage-fivem-sp

Error message is then like this
[[13:41:50][Error] Error on asset reading. Collection [RawStreamer], readedBytes = 4294967295, lastFileReadBytes = 0[Error] Error on asset reading. Collection [RawStreamer], readedBytes = 4294967295, lastFileReadBytes = 0[13:41:50]
[Failed to reload map store, asset: fruzze_garage_ls/INVALID-ASSET-ID exception code: 13:3221225477 41
  Could be caused by a faulty asset file:
  This could cause future issues, please report this error[ Failed to reload map store, asset: fruzze_garage_ls/INVALID-ASSET-ID exception

The message looks like a DLC error, but it doesn't make much sense if it's been on prod for months.

Error 2:
After switching containerization on once and then switching it off again, the “size to download” remains at the maximum download size (in our case ~10 GB) after a resource change
But as soon as you have downloaded the changed resource, you join the server.

The same behavior, that you are shown more than you actually download, is also the case when containerization is switched on, which is not too bad, but it just causes confusion

### Reproduction steps

Error 1:
Load Resource on Server, Switch on Resource Containerization, connect (and crash after the queue)

Error 2:
Switch Resource Containerization on, download all assets, Switch it off, change something in a resource, restart server, reconnect

### Expected behaviour

Error 1:
That Resources that work on turned Containerization turned off, also work when its turned on

Error 2:
That you only see the size of the resources to be downloaded, not the total size of all resources on the server

### Operating system

Server: Ubuntu 24.10 ; Client: Windows 10 22H2

### Version

16.2.24 (release) and 16.2.25-rc.3

### Crashdump ID

39861353-d397-4e6f-aa6b-806eee5c1e69

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by shloooo** [comment] 2024-11-21 21:51
Well, it's just a duplicate of #2369 and #2371

**Comment by TheOutburst** [comment] 2024-11-21 21:53
welp. yeah. oops

**Comment by Doxoh** [comment] 2024-11-22 06:44
will be closed because double. But its linked

**Closed as completed by Doxoh** 2024-11-22 06:44 UTC
Labels: Class: bug
