### ISSUE TITLE
Object api constructor cause crash

### ISSUE THREAD

**Issue by Konders** [altmp/altv-issues#1599] opened 2022-08-08 14:37 UTC
### Description of the problem

Crash occured on line `object = new alt.Object(alt.hash("p_amb_phone_01"), { ...localPlayer.pos }, { ...localPlayer.rot }, false, true);`
Reproducible rate 100%
needs to spawn phone from 1 to 4 times to reproduce
Crash dump was not created so i cant provide it

### Reproduction steps
Code:
`let object;
const localPlayer = alt.Player.local;
alt.on("keydown", (key) => {
	if (key == 38) {//arrow up
		if (object) {
			object.destroy();
			object = undefined;
		} else {
			object = new alt.Object(alt.hash("p_amb_phone_01"), { ...localPlayer.pos }, { ...localPlayer.rot }, false, true);
			alt.Utils.waitFor(() => object.isSpawned).then(() => {
				let boneIndex = game.getPedBoneIndex(localPlayer, 57005);
				object.attachToEntity(
					localPlayer,
					boneIndex,
					{ x: 0.15, y: 0.0, z: -0.043 },
					{ x: 15.0, y: 80.0, z: 150 },
					false,
					false,
					true
				);
			});
		}
	}
});`

Press key "arrow up" to spawn phone
Press key "arrow up" to destroy phone

Reproduction still available even with commented all code block of waiting to be spawned and to be attached
### Expected behaviour

Object correctly create

### Operating system

Windows 11

### Version

13.0-dev8

**Comment by LeonMrBonnie** [comment] 2022-08-08 14:39
Duplicate of #1595

**Closed by LeonMrBonnie** 2022-08-08 14:39 UTC
Labels: Class: bug
