### ISSUE TITLE
Add programmatically downloadable client-side files

### ISSUE THREAD

**Issue by VnX-SolidSnake** [altmp/altv-issues#635] opened 2020-09-04 22:28 UTC
**Suggestion**
Dear alt:V Team,
i think it would be good if we can create Clientside via JS Code Files for our clients...

**Use cases**
Situation A : you have a multigamemode server like us... the client can select which gamemode he will download and don't have to download 9 gamemode scripts with all the images, textures, sounds etc ?

Situation B : The Server don't have to store all the useless data in the Database... think about it ... 
The Client have a iPhone 11 (or whatever .. )  in his RP Gamemode... and he changed his iPhone11 Wallpaper... 
Server Owners gonna have to add this ,,wallpaper change" to the Database...
with this feature the server owner can create a simple ,,config.txt" file via JS Client code inside his Client Resource folder... that is loading everytime... no needed Database entry + no one cares about a config file... the only thing will be : if he deletes locally his resource folder... the config will be gone... so this feature is good to store the useless data's or download Files/Scripts only if its needed...

**Describe the solution you'd like**
i thought something like :  
```js
alt.downloadFile('path/script.js');
alt.downloadFile('path/sound.mp3');
alt.downloadFile('path/image.png');
```

**Describe alternatives you've considered**
or you can have something like a XML File where you put all these files in.. ? 
```xml
<cdn src="path/script.js"></cdn>
<cdn src="path/sound.mp3"></cdn>
<cdn src="path/image.png"></cdn>

```
something like that maybe..

**Additional context**
~ Solid

**Comment by martonp96** [comment] 2020-09-04 22:58
I will add something like alt.startResourceForPlayer on server side.
https://altmp.github.io/altv-typings/modules/_alt_server_.html#startresource

With that you will be able to load asset packs for individual players in runtime.

**Comment by FabianTerhorst** [comment] 2020-09-04 23:04
Duplicate of #39

**Comment by FabianTerhorst** [comment] 2020-09-04 23:10
Download is already possible to implement via express, aspnet core ect. The only feature request i see here is a larger local storage via permission system.

**Closed** 2020-09-06 21:07 UTC
Labels: Class: enhancement, Scope: module-api, Side: server
