### ISSUE TITLE
Adding weaponShot or extending weaponChange event for ammunition tracking

### ISSUE THREAD

**Issue by tastydev** [altmp/altv-issues#679] opened 2020-11-02 18:33 UTC
**Suggestion**
Since there are many edge cases to handle currently to track bullets/ammo of  players it would be nice to see this feature inside the alt:V api.

**Use cases**
Correct and easy tracking of ammunition amounts

**Describe the solution you'd like**
Since the server currently already knows ammo amounts and since empty weapon sound click is synced as well it would nice to see a `weaponShot` event with `oldAmmo`,  `newAmmo` and `weaponHash` or an ammo param inside the `weaponChange` event

**Describe alternatives you've considered**
Designing ugly own clientside events through everyTick/interval checks to check ammunition of the current weapon and disabling ped tasks to stop the automated weaponswitch of the game. This is really bad cause u somehow rely on clientside data.

**Additional context**
This would also help to resolve issue #667 which was a feature request to track the last bullet that got shot before the game unequips the empty weapon. I still would like to see both requests inside the api.

**Comment by ThomasMarangoni** [comment] 2020-11-02 18:35
duplicate of #1 , but with better describtion

**Comment by Lhoerion** [comment] 2020-11-02 18:46
I remember talk about adding similar event, possible to add is event when weapon starts shooting and when it's stop. Otherwise it's a waste of traffic

**Comment by FabianTerhorst** [comment] 2020-11-02 20:41
Afaik server has that info already. It just need to be parsed.

**Comment by tastydev** [comment] 2020-11-02 20:42
it´s not a waste of traffic the information is already there on serverside

**Comment by Lhoerion** [comment] 2020-11-02 21:20
> it´s not a waste of traffic the information is already there on serverside

That's what devs spoke some time ago, not my words

**Comment by tastydev** [comment] 2020-11-02 22:12
Found btw on discord that tuxick already told its possible and sent already.
[tuxick statement](https://discord.com/channels/371265202378899476/547079158300147725/746030725425266769)

**Comment by Lhoerion** [comment] 2020-11-02 22:15
> Found btw on discord that tuxick already told its possible and sent already.
> [tuxick statement](https://discord.com/channels/371265202378899476/547079158300147725/746030725425266769)
It doesn't matter, I'm not the one implementing said feature, also not kinda up to me that someone can change his mind

**Comment by tastydev** [comment] 2020-11-02 22:17
Why do u feel offended? I am posting this for documentary not to blame u :P

**Comment by Lhoerion** [comment] 2020-11-02 22:42
Nah, not offended but kinda continuing the conversation regarding it? 😃

**Comment by KooperNinja** [comment] 2022-06-20 07:34
> Afaik server has that info already. It just need to be parsed.

Is this possible to add in the next update? Would be really great

**Comment by FabianTerhorst** [comment] 2023-06-17 09:34
Ammo getter / setter is now available in 15.0 dev.

**Closed by FabianTerhorst** 2023-06-17 09:34 UTC
Labels: Class: enhancement, Side: server, Scope: module-api
