### ISSUE TITLE
Wildcard for resources

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1504] opened 2022-06-06 11:49 UTC
### Description of the problem

Add Wildcard feature for resources in `server.cfg`.

### Desired solution for the problem

```yaml
resources: [
    folder1/*
    folder2/folder3/*
    folder4/folder5/folder6/*
    script1
    folder7/script2
]
```

**Comment by Phill030** [comment] 2022-06-06 12:20
Looks like a duplicate of #1485

**Comment by C0kkie** [comment] 2022-06-06 12:28
Clientfiles and ressource config is different

**Comment by C0kkie** [comment] 2023-05-26 19:17
Possible in v15

**Closed by C0kkie** 2023-05-26 19:17 UTC
Labels: Class: enhancement
