### ISSUE TITLE
Helicopters falling through floor/collision + causing random explosions sometimes (and possibly client crashes)

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1305] opened 2022-01-01 23:47 UTC
### Description of the problem

Since the last GTA update that broke alot of sync stuff, we've noticed helicopters falling thru roofs of buildings etc and getting (partially) stuck inside the building. When the heli streams in for a player, it explodes (not always).

Some players have even reported hearing a random explosion in the distance just before their game crashes, could be related to this.

### Reproduction steps

No idea really. Spawn a helicopter on eg mission row PD(happened here the most for us).

When going there, the heli falls thru floor and ends up inside the interior.

### Expected behaviour

The heli to not fall thru collision

### Additional context

Never happened before GTA update(altV 8).

### Operating system

Ubuntu 20.04 (server), Windows 10 (client)

### Version

Release 8.8

**Comment by C0kkie** [comment] 2022-01-03 22:23
Can confirm it https://streamable.com/0mwxl9

**Comment by FabianTerhorst** [comment] 2022-01-04 01:26
Sounds like #272

**Comment by C0kkie** [comment] 2022-01-04 10:01
Dont think so @FabianTerhorst  cuz that bug is new

**Comment by CoffeeGen** [comment] 2022-01-04 10:02
Yeah never saw this happen before the last GTA update. Now it's pretty common

**Comment by FabianTerhorst** [comment] 2022-01-04 10:27
Does it only happen on mlo's?

**Comment by CoffeeGen** [comment] 2022-01-04 10:31
Nope also regular buildings etc. It just gets stuck inside it. Then either explodes (on streamin?) Or stays there until respawn. Can also be part of the heli(eg front half stuck inside building, rear half sticking out of building)

**Comment by spkesDE** [comment] 2022-01-04 14:05
Can also confirm it. We have the same issue since the GTA V update. Even when there are on the ground.

**Comment by zziger** [comment] 2022-01-05 16:42
Happens for me too

**Comment by CoffeeGen** [comment] 2022-01-07 01:38
Also seems to cause server crashes when the server tries to delete a vehicle that just exploded (c# api)

**Comment by Rodhin** [comment] 2022-01-07 14:12
We have this issue too, both on the top of Mission Row PD and on the top of Pillbox Hospital.

**Comment by alphasylvain** [comment] 2022-02-04 16:34
> We have this issue too, both on the top of Mission Row PD and on the top of Pillbox Hospital.

me too

**Comment by xxshady** [comment] 2022-04-02 17:10
I can also reproduce this bug very easily on empty server

**Comment by silentninja2** [comment] 2022-04-08 23:36
We also had this issue execpt one position. At the airport in the city the vehicles stayed and didn't explode. So not sure if it's something about on what ground the vehicles are.

**Comment by C0kkie** [comment] 2022-05-01 15:35
Fixed in dev/10.0-dev18

**Closed by C0kkie** 2022-05-01 15:35 UTC
Labels: Class: bug, Side: client, Status: confirmed
