### ISSUE TITLE
ServerEvent "VehicleDamage"

### ISSUE THREAD

**Issue by lameule123** [altmp/altv-issues#636] opened 2020-09-05 14:28 UTC
**Suggestion**
Add a simple server event wich is trigger when vehicle get damaged.
Same as PlayerDamage event.

**Describe the solution you'd like**
on(eventName: "VehicleDamage", listener: (vehicle: Vehicle) => void): void

**Comment by FabianTerhorst** [comment] 2020-09-05 14:48
Duplicate of #45

**Closed by FabianTerhorst** 2020-09-05 14:48 UTC
Labels: Class: enhancement
