### ISSUE TITLE
player.invicible setter broken

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1297] opened 2021-12-28 11:59 UTC
### Description of the problem

player.invincible = true; does not workd. Player is getting damage

### Reproduction steps

set player invincible and do damage to the player. he will take damage

### Expected behaviour

player should not take damage when invincible

### Additional context

none

### Operating system

debian 10

### Version

release 8.6

**Comment by YannBCF** [comment] 2022-01-03 23:02
Can you add details on what actually make the players take damages when setting the invincible setter to true ?

**Comment by zziger** [comment] 2022-01-03 23:10
We cannot reproduce this issue, can you please add exact reproduction steps?

**Comment by cmdflow** [comment] 2022-01-06 10:04
I could kill a player shooting on him. Maybe fixed in a later realease? Can't test atm

**Comment by C0kkie** [comment] 2022-01-19 23:07
@cmdflow  Can you try with newest rc build?

**Comment by LeonMrBonnie** [comment] 2022-02-19 02:19
We were not able to reproduce this and the issue author has not given any more info on helping us reproduce this, so I am closing the issue.
If you have any info to help us confirm it, feel free to post it here, and then the issue will be reopened.

**Closed by LeonMrBonnie** 2022-02-19 02:19 UTC
Labels: Class: bug, Side: client, Status: question, Scope: internal
