### ISSUE TITLE
Swapped “tuning parts” on the Vulcar Nebula Turbo

### ISSUE THREAD

**Issue by banbu123** [altmp/altv-issues#2376] opened 2024-11-23 14:45 UTC
### Description of the problem

Tuning parts are swapped or not assigned on the Vulcar Nebula Turbo since the big update in January (I think I have no idea about the whole technical stuff and try to explain it as good as I can :D ) But this does not affect the rims and paintwork.

For example, if I change the engine, a spoiler is put on the car. Many other options have no effect at all
![GTA5 2024-11-23 15-41-32](https://github.com/user-attachments/assets/a7321bb2-5d7e-4701-8f72-d63d0dbc968d)

The screenshot was not taken on the server I play on but on playv. I can post a before and after picture of how the Nebula looks/looked on the server

it's not a server problem either, because the server team already tried to reassign it which didn't work. And it is the same on several servers.

### Reproduction steps

By selecting the engine, for example, it changes the spoiler. 

### Expected behaviour

That the tuning parts are assigned correctly again. I hope that it is possible :3

### Operating system

Windows

### Version

on every version since the 16.0 update in january 

### Crashdump ID

No crashes

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by shloooo** [comment] 2024-11-23 15:34
Duplicate of #2364

**Comment by shloooo** [comment] 2024-11-23 15:35
@Doxoh

**Closed as completed** 2024-11-23 16:43 UTC
Labels: Class: bug
