### ISSUE TITLE
WebView Instances not Destroyed

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#1285] opened 2021-12-22 17:48 UTC
### Description of the problem

Currently WebView instances are not being destroyed on disconnect. They sometimes do destroy but often times you end up with additional altv-webengine executables.

![](https://i.imgur.com/nIGgk17.png)

### Reproduction steps

```ts
const view = new alt.WebView('https://google.com/');

alt.on('disconnect', () => {
    view.destroy();
});
```

### Expected behaviour

They get destroyed either by default through connection loss, or we can invoke the destroy through the disconnect event.

### Operating system

Windows 10

### Version

*

**Comment by C0kkie** [comment] 2022-01-19 23:11
Can you try on latest rc? pretty sure we fixed something there @Stuyk

**Comment by dominion56** [comment] 2022-02-09 16:23
same thing on 9.4 Release

**Comment by FileCode** [comment] 2022-02-10 06:55
and 9.5 on dev rel and rc

**Comment by LeonMrBonnie** [comment] 2022-02-10 20:17
I am unable to reproduce this issue with the provided reproduction steps

**Comment by LeonMrBonnie** [comment] 2022-02-25 22:04
Wasn't able to reproduce and no response from the issue author so I will close this issue.

**Comment by C0kkie** [comment] 2023-04-25 12:09
Should be fixed in newest dev

**Closed by C0kkie** 2023-04-25 12:09 UTC
Labels: Class: bug, Side: client, Status: confirmed, Scope: webview
