### ISSUE TITLE
Opening client console while shooting will keep player shooting forever

### ISSUE THREAD

**Issue by edgarasx** [altmp/altv-issues#2278] opened 2024-05-09 15:31 UTC
### Description of the problem

LMB/RMB buttons get stuck if player enters any altv menu while already pressing them. Then once a menu is opened they can release those buttons and the game does not seem to record that, so for example when client console is closed down the game continues to return true for a control press in the natives even though the player is no longer pressing anything.

### Reproduction steps

1) Equip any weapon.
2) Press either LMB or RMB.
3) While pressing, open console with F8 or alt:V menu with F1 or disable `alt.toggleGameControls` in code.
4) Once the menu is opened you can release the button. The player continues to aim/shoot, even if you close the menu.

The issue is that if player closes the console they can continue to shoot without pressing anything and functions such as `native.isControlPressed` will continue to return true even if player is not pressing anything at all. I tried lots of natives to stop player from shooting, but nothing works. The issue only seems to occur with mouse buttons.

### Expected behaviour

When alt:V menu/client console is opened or `alt.toggleGameControls` is used the player should stop using LMB/RMB.

### Operating system

Windows

### Version

16.0.155 (release)

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by xxshady** [comment] 2024-05-09 15:48
duplicate of #808

**Closed by xxshady** 2024-05-09 15:48 UTC
Labels: Class: bug
