### ISSUE TITLE
Vehicle rot setter teleports vehicles

### ISSUE THREAD

**Issue by vrtoday** [altmp/altv-issues#700] opened 2020-11-13 16:29 UTC
**Client/server version**

`Build 2.1-rc1 (rc), branch rc`

**Current behavior**

When I set rotation to a veh (veh.rot = new alt.Vector3(veh.rot.x, veh.rot.y, veh.rot.z + 0.1)) it teleports to one of nearest vehicle.

video
https://vimeo.com/478980632

**Expected behavior**

Just set rotation

**Steps to reproduce**

1. spawn some cars
2. set rotation for a car

`veh.rot = new alt.Vector3(veh.rot.x, veh.rot.y, veh.rot.z + 0.2)`

Also it works ok only if I go away from vehicles (maybe client-side trouble?). 

**Context (environment)**

It brokes a lot of mechanics in the server, all mechanics where i set the vehicle rotation, all vehicle teleports. It is critical for me, i have try to change server branch to release

**Possible solution**

Don't know, it is looks like client side trouble because if veh isnt in my streamzone it sets ok.

**Comment by tastydev** [comment] 2020-11-13 16:34
duplicate of #585

**Comment by Lhoerion** [comment] 2020-11-13 16:56
It's not duplicate, it's separate proper issue but in relation to #585

**Comment by martonp96** [comment] 2020-12-06 11:45
This is fixed in dev.

**Closed by martonp96** 2020-12-06 11:45 UTC
Labels: Class: bug, Priority: critical, Scope: internal, Side: server, Status: fix-pending
