### ISSUE TITLE
Setting vehicle part damage level doesn't work

### ISSUE THREAD

**Issue by LeonMrBonnie** [altmp/altv-issues#571] opened 2020-06-14 19:28 UTC
When you set the damage level of a vehicle part using `vehicle.setPartDamageLevel` the damage gets applied, but reset on the next tick.

I try to set the damage on my vehicle when it is spawned, but it gets reset.

**Expected behavior**

The vehicle damage stays applied and is visible.

**Current behavior**

The vehicle damage gets reset on next tick.

**Possible solution**

/

**Steps to reproduce**

Create a vehicle, set damage level with `vehicle.setPartDamageLevel(part, level)`
Instantly log the damage levels with `vehicle.getPartDamageLevel(part)`
Log the damage levels after a timeout of 1ms

**Context (environment)**

I tried to load the vehicle damage from the database and apply it on the vehicle.

**Detailed description**

/

**Possible implementation**

/

**Comment by FabianTerhorst** [comment] 2020-06-14 19:33
Duplicate of #371

**Closed by FabianTerhorst** 2020-06-14 19:33 UTC
Labels: Class: bug

**Comment by SamDavid93** [comment] 2021-11-10 04:04
Any alternative available?
