### ISSUE TITLE
Some properties of IVehicleHandling not change

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#997] opened 2021-07-04 16:15 UTC
**Client/server version**
`Build #2.24, branch release`

**Current behavior**
Some properties of `IVehicleHandling` interface not working at all.
It is better to check all the properties of `IVehicleHandling` again.
```js
// Determines how many forward speeds/gears a vehicle's transmission contains.
alt.Player.local.vehicle.handling.initialDriveGears = 2;

// The weight of the vehicle.
alt.Player.local.vehicle.handling.mass = 100.0;
```

**Expected behavior**
The number of gears must be reduced to 2 and the weight of the vehicle must be changed to 100kg.

**Comment by FabianTerhorst** [comment] 2021-07-04 16:41
Duplicate of #684 . Add the mass there as a comment.

**Closed by FabianTerhorst** 2021-07-04 16:41 UTC
Labels: Class: bug, Scope: internal, Side: client, Status: to-investigate
