### ISSUE TITLE
Chunking of resource files for CDN

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1602] opened 2022-08-09 21:35 UTC
### Description of the problem

Currently Cloudflare alongside with some other CDN providers have a limit of 512MB per file in cache

### Desired solution for the problem

Some argument that would force --justpack to chunk resources, and support of chunked resources in the client

**Comment by LeonMrBonnie** [comment] 2022-08-09 21:36
Duplicate of #1373

**Closed by LeonMrBonnie** 2022-08-09 21:36 UTC
Labels: Class: enhancement
