### ISSUE TITLE
CEF/F8 Freeze

### ISSUE THREAD

**Issue by gt4ever1988** [altmp/altv-issues#1120] opened 2021-09-16 19:47 UTC
**Client/server version**
rc/6.0-rc12

**Current behavior**
After a while, the CEF freezes with its entire content. As soon as this occurs, F8 no longer works either (console does not open). This behavior occurs from time to time, more often when a player dies or is injured in the vicinity.

**Comment by FabianTerhorst** [comment] 2021-09-16 19:58
Please provide code to reproduce.

**Comment by gt4ever1988** [comment] 2021-09-16 20:03
Unfortunately, this is coincidental, even if you only drive the vehicle. When driving a vehicle, I only update the street name and vehicle speed, which stops at once. I do this via an "emit" to an "alt.WebView" without destroying the WebView - it is only created once and fired permanently. After the vehicle speed or street name doesnt refresh also the F8 doesnt load.

**Comment by C0kkie** [comment] 2021-09-16 22:20
I can confirm that, but its hard to reproduce it, i also just tabbed out and came back after few minutes and it freezed

**Comment by C0kkie** [comment] 2021-09-17 02:21
@gt4ever1988  Should be fixed in rc/6.0-rc12, please report back if its fixed for you

**Comment by gt4ever1988** [comment] 2021-09-17 13:29
Still occurs with 6.0-rc14, but much less often

**Comment by gt4ever1988** [comment] 2021-09-17 14:48
After some tests, the bug occurs when the player takes damage in a vehicle / or is thrown from the vehicle (but does not die in the process). In the current test, however, this only occurs 1/20 attempts!

**Comment by gt4ever1988** [comment] 2021-09-17 15:28
If a player is killed several times and he is automatically resuscitated (purely for the test) he will not be resuscitated after a while - from this moment the CEF no longer works // in this case F8 continued to work

https://www.youtube.com/watch?v=VarPrZjDc_o

**Comment by FabianTerhorst** [comment] 2021-09-17 15:30
Sound very much depending on your Code.

**Comment by UnskilledFreak** [comment] 2021-09-17 21:34
I found something related to the CEF freezes and answered on a similar topic in #1096 
i guess this fits here to, so here is the direct link: https://github.com/altmp/altv-issues/issues/1096#issuecomment-922087251

**Comment by n0minal** [comment] 2021-09-27 19:48
seems to be fixed in latest rc branch for me.

**Comment by C0kkie** [comment] 2021-09-27 19:51
Nice thanks for your feedback

**Closed by C0kkie** 2021-09-27 19:51 UTC
Labels: Class: bug, Side: client, Status: confirmed, Status: question, Scope: webview
