### ISSUE TITLE
DEV | AltV Client main menu not loading

### ISSUE THREAD

**Issue by MauriceWit** [altmp/altv-issues#1328] opened 2022-01-14 21:07 UTC
### Description of the problem

Hi, when im start the develop client of alt:V the main menu didn't get loaded properly. All i see is literally only a black screen.

### Reproduction steps

Steps i tried (all with clean / fresh installment of alt:V):

- Download alt:V Client, start Release client and closed. Then change branch to 'dev' and load the new client - black screen after gta loaded.
- Download alt:V Client, changed branch directly to 'dev' and load the new client - black screen after gta loaded.

### Expected behaviour

Should the see the menu of alt:V

### Additional context

With the release client there is no such a problem.

PC Specs:

![image](https://user-images.githubusercontent.com/93884145/149585068-16d52f85-ad52-4214-81cc-5b272a029481.png)
![image](https://user-images.githubusercontent.com/93884145/149585180-b9609742-5e33-4d62-8333-e069ca078295.png)

Log files:
[client_14-01-2022_21-44-50.log](https://github.com/altmp/altv-issues/files/7873217/client_14-01-2022_21-44-50.log)
[cef.log](https://github.com/altmp/altv-issues/files/7873219/cef.log)
[launcher.log](https://github.com/altmp/altv-issues/files/7873221/launcher.log)

### Operating system

Windows 10

### Version

dev-8

**Comment by Baldrge** [comment] 2022-01-14 21:13
Hey, i am having the same issue with the dev 9.0 rev 8 client. 

The release version of altv is working without this issue.

[client_14-01-2022_21-55-40.log](https://github.com/altmp/altv-issues/files/7873244/client_14-01-2022_21-55-40.log)
[cef.log](https://github.com/altmp/altv-issues/files/7873246/cef.log)
[launcher.log](https://github.com/altmp/altv-issues/files/7873247/launcher.log)


Operating system: 
Windows 11

![image](https://user-images.githubusercontent.com/93787936/149585921-11c8d761-7326-43f1-8d39-9ea3600e21dc.png)
![image](https://user-images.githubusercontent.com/93787936/149585950-ca9b63d8-88ab-42d5-9c9b-dcd9c2c90bf7.png)

**Comment by juztim** [comment] 2022-01-15 00:47
@Baldrge do you use the same driver version as @MauriceWit ?

**Comment by Baldrge** [comment] 2022-01-15 07:11
Yes.
![image](https://user-images.githubusercontent.com/93787936/149613089-3c5b200f-dd68-4c8f-abc7-d09d7fab689b.png)

**Comment by Revyn112** [comment] 2022-01-15 07:46
I'm using the same driver version and don't have the problem over here (RTX3070).

**Comment by Baldrge** [comment] 2022-01-15 07:59
I am having the same issue also with the new version from yesterday:
![image](https://user-images.githubusercontent.com/93787936/149614432-e5c32b05-11f4-4602-84e3-cf61f90f30d0.png)

**Comment by martonp96** [comment] 2022-01-15 10:18
@Baldrge @MauriceWit  please try with dev9 and send me the client log file

**Comment by Baldrge** [comment] 2022-01-15 13:35
[client_15-01-2022_14-32-48.log](https://github.com/altmp/altv-issues/files/7875053/client_15-01-2022_14-32-48.log)
Its still the case with dev9

**Comment by martonp96** [comment] 2022-01-17 07:00
@MauriceWit @Baldrge please test with dev10

**Comment by Baldrge** [comment] 2022-01-17 09:38
[client_17-01-2022_10-36-04.log](https://github.com/altmp/altv-issues/files/7880735/client_17-01-2022_10-36-04.log)
no changes with dev10

**Comment by MauriceWit** [comment] 2022-01-17 17:29
It's not working for me eithe

[client_17-01-2022_18-21-02.log](https://github.com/altmp/altv-issues/files/7883784/client_17-01-2022_18-21-02.log)

**Comment by martonp96** [comment] 2022-01-18 05:24
@MauriceWit @Baldrge i see you both have some weird dlls loaded from your game folder:

[18:21:02] E:\GTA 5 Alt V\GTAV\D3D11.DLL
[10:36:05] C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\D3D11.DLL

Do you have any graphic mods installed? What happens if you remove those dlls and try to start the game?

**Comment by martonp96** [comment] 2022-01-18 06:53
anyways, please try with dev11

**Comment by Baldrge** [comment] 2022-01-19 10:06
dev11 is working
![image](https://user-images.githubusercontent.com/93787936/150108711-2cab270c-e873-4fb2-8f1b-641cb2ba2858.png)
[client_19-01-2022_10-59-58.log](https://github.com/altmp/altv-issues/files/7896057/client_19-01-2022_10-59-58.log)

I still add the log in case you need some information from it. 

Mods i use: 
NVE and enb/reshade shaders
These dont produce issues with the release version. However i also tried with vanilla before.

**Comment by martonp96** [comment] 2022-01-19 14:52
Seems like the issue is now fixed, thank you for the help

**Closed by martonp96** 2022-01-19 14:52 UTC
Labels: Class: bug, Side: client, Status: to-investigate, Scope: internal

**Comment by MauriceWit** [comment] 2022-01-19 15:25
Yes, it works for me now too
