### ISSUE TITLE
Possibility to customize the path for log files

### ISSUE THREAD

**Issue by TheFruchtiHD** [altmp/altv-issues#1388] opened 2022-02-24 14:51 UTC
### Description of the problem

Currently, only one log file is created for the server and overwritten on restart. It would be helpful if a separate log file is created for each server start to keep log data after server restarts.

### Desired solution for the problem

A server launch option to set the path. Create a log file at server startup named by date and time.

### Additional context

The option is already present in the documentation. However, according to a conversation in the Discord support-help channel, it is probably not implemented in altv at all.

**Comment by FabianTerhorst** [comment] 2022-02-24 14:52
Duplicate of #369

**Closed by FabianTerhorst** 2022-02-24 14:52 UTC
Labels: Class: enhancement
