### ISSUE TITLE
CEF Input-Cursor not blinking in iframes

### ISSUE THREAD

**Issue by gt4ever1988** [altmp/altv-issues#1119] opened 2021-09-16 19:45 UTC
**Client/server version**
rc/6.0-rc12

**Current behavior**
When a CEF is opened in which an input, text area or other input option is available, the text cursor is not displayed. By text cursor I mean the line that flashes to identify the position of the text character. In F8-Console the text cursor works.

**Comment by zziger** [comment] 2021-09-16 20:57
Do you use data: urls somewhere in your code?

**Comment by lokuPadoku** [comment] 2021-09-17 06:11
I have the same problem with rc/6.0-rc13. I'm not using any data: urls but iframes.

**Comment by FabianTerhorst** [comment] 2021-09-17 07:44
Does it also happen outside of a iframe?

**Comment by lokuPadoku** [comment] 2021-09-17 11:09
No

**Comment by gt4ever1988** [comment] 2021-09-17 12:07
Same issue on 6.0-rc14

**Comment by eiksch** [comment] 2021-09-17 13:18
can confirm on 6.0-rc14

my mousewheel isnt working to inside <iframe>. I need to grab scrollbar manually with mouse.

**Comment by ThomasMarangoni** [comment] 2021-09-17 13:24
> can confirm on 6.0-rc14
> 
> my mousewheel isnt working inside <iframe> too, can someone confirm? I need to grab scrollbar manually with mouse.

please create a separate issue

**Comment by gt4ever1988** [comment] 2021-09-27 19:40
Same issue on rc/6.0-rc16

https://youtu.be/Pn5aPBsLTRM

_>> Maybe the same from 1061? (A bug in cef and was only present in release branch)_

**Comment by vadzz-dev** [comment] 2021-09-27 20:17
Cannot reproduce it with a simple webview with iframe. Both scroll & input cursor work fine on 6.0-rc16

**Comment by DurtyFree** [comment] 2021-09-29 09:40
@gt4ever1988 Can you pls provide a alt:V resource that can reproduce this issue?

**Comment by gt4ever1988** [comment] 2021-09-29 17:20
I have now tried 3 variants:
1) Open CEF / there is direct a input in the HTML ... **works perfectly**
2) Open CEF / in the HTML there is an iFrame which is an HTML which is also in the resources. There is an input in it ... **works perfectly**
3) Open CEF / in the HTML there is an iFrame which loads an external website. There is an input in it (the same HTML as in point nr. 2 ... **Cursor does not blink**

Here is example no.3:


**startscript.js**
`let cef = new alt.WebView('http://resource/ui/index.html'); cef.focus();`

**ui/index.html**
`<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><iframe id="bodyFrame" style="width:100vw;height:100vh;" src="https://www.LinkToExternalWebsite.de/index.html"></iframe></body></html>`

**index.html (on Webserver)**
`<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><input type="text" name="test" value="" /></body></html>`

**Comment by Xantron** [comment] 2021-10-02 02:03
Same Problem. No cursor. No Login on extern webviews / iFrame

**Comment by seelrd** [comment] 2021-10-30 12:52
In the same situation (remote iframes) input focus and unfocus events do not work either.

**Comment by pixlcrashr** [comment] 2021-10-30 12:58
Can reproduce that.

**Comment by pixlcrashr** [comment] 2021-10-30 13:21
#1193 (maybe) relate to the same root cause.

**Comment by Revyn112** [comment] 2022-01-04 19:35
Still a problem in release/8.8 https://img.revyn112.dev/data/LG95BRmJpx.mp4

**Comment by Revyn112** [comment] 2022-04-29 19:27
The same will happen when the url will change through webview url parameter.

**Comment by Hardy535** [comment] 2022-08-07 18:06
This still seems to be an issue. The cursor is not appearing in input fields and are not focused/blurred.
I'm not using any iframes but some redirects to external websites.
Strangely after a reconnect it sometimes works for me.

**Comment by FabianTerhorst** [comment] 2023-02-23 00:47
Fixed in ```dev/14.0-dev54```.

**Closed by FabianTerhorst** 2023-02-23 00:47 UTC
Labels: Class: bug, Side: client, Status: confirmed, Scope: webview
