### ISSUE TITLE
WebView | Iframe / Object | Input fields aren't focused / site not scrollable anymore after interaction

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#1310] opened 2022-01-04 19:27 UTC
### Description of the problem

When you bind a external website via Iframe or Object you don't have feedback over a input field because when click in it there will be no blinking cursor. Also when you interact with a iframe / object you can't scroll anymore.

### Reproduction steps

```
<iframe src="https://ucp.gtalife.net/" width="1000px" height="1000px">
iframe not working
</iframe>
```

```
<object data="https://ucp.gtalife.net/" width="1000px" height="1000px">
object not working
</object>
```

### Expected behaviour

Input field should focus as normal and general scroll should be working as normal.

### Operating system

Windows 11

### Version

release/8.8

**Comment by C0kkie** [comment] 2022-01-04 19:28
Duplicate of #1119

**Closed by C0kkie** 2022-01-04 19:28 UTC
Labels: Class: bug
