### ISSUE TITLE
Textlabel Enhancement

### ISSUE THREAD

**Issue by hookmethods** [altmp/altv-issues#1981] opened 2023-09-02 14:19 UTC
### Description of the problem

There's no text/fontsize/fontstyle setter for a existing label

### Desired solution for the problem

Add the ability to change the text / fontSize / fontFamily immediately. for now, I have to create a new one to update these properties

**Comment by Lukascc** [comment] 2023-10-27 16:10
up up up

**Comment by zziger** [comment] 2023-11-22 10:50
Duplicate of #1964

**Comment by zziger** [comment] 2023-11-22 10:53
Setters are implemented with #1964, and will be merged to dev soon

**Comment by ThomasMarangoni** [comment] 2023-11-28 17:28
Added in latest dev

**Closed by ThomasMarangoni** 2023-11-28 17:28 UTC
Labels: Class: enhancement
