### ISSUE TITLE
Crash after spawning a second object via new Object API

### ISSUE THREAD

**Issue by ithr0n** [altmp/altv-issues#1596] opened 2022-08-07 19:48 UTC
### Description of the problem

The client crashes after you try to spawn a second object via the new Object API.

### Reproduction steps

Execute it twice:

```// client file
const p = alt.Player.local;
const tank = new alt.Object("p_d_scuba_tank_s", p.pos, p.rot, true, false)
const tankBone = natives.getPedBoneIndex(p, 24818)
const tankPos = { x: 0, y: 0, z: 0}
const tankRot = { x: 0, y: 90, z: 180}
tank.attachToEntity(p, tankBone, tankPos, tankRot, false, false, true)

alt.log(tank.id)
alt.log(tank.scriptID)```

### Expected behaviour

Two object should spawn.

### Additional context

_No response_

### Operating system

Windows 10

### Version

#13.0-dev8

**Comment by chaosfreak93** [comment] 2022-08-07 19:50
Duplicate of #1595

**Closed** 2022-08-07 19:51 UTC
Labels: Class: bug
