### ISSUE TITLE
alt.Checkpoint is borken

### ISSUE THREAD

**Issue by Cyuancai** [altmp/altv-issues#2117] opened 2023-11-12 16:16 UTC
### Description of the problem

jobPoint = new alt.Checkpoint(47, 2748.1318359, 1453.094, 24.494506 - 1, 1, 1, 255, 0, 0, 155, 400);
jobPoint valid but didnt show in game

### Reproduction steps

`jobPoint = new alt.Checkpoint(47, 2748.1318359, 1453.094, 24.494506 - 1, 1, 1, 255, 0, 0, 155, 400);`
enter game, check visible

### Expected behaviour

jobPoint is visible

### Operating system

win 11

### Version

release #15.57 & dev 15#866

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment] 2023-11-12 16:18
(was confirmed before v15 release)

**Comment by FabianTerhorst** [comment] 2023-11-12 16:18
Duplicate of #2024

**Closed by FabianTerhorst** 2023-11-12 16:18 UTC
Labels: Class: bug, Status: confirmed
