### ISSUE TITLE
Add createWorldObject on the serverside

### ISSUE THREAD

**Issue by Whitee303** [altmp/altv-issues#1418] opened 2022-03-29 09:55 UTC
### Description of the problem

This would provide the ability to create synchronized objects on the serverside.

For example in mta looks like this:
https://wiki.multitheftauto.com/wiki/CreateObject

### Desired solution for the problem

`let object = new alt.Object(hash,posx,posy,posz,rot)`

**Comment by FabianTerhorst** [comment] 2022-03-29 09:56
Duplicate of #121

**Closed by FabianTerhorst** 2022-03-29 09:56 UTC
Labels: Class: enhancement
