### ISSUE TITLE
gameFocusChange EVENT

### ISSUE THREAD

**Issue by risvensh** [altmp/altv-issues#1393] opened 2022-02-27 00:30 UTC
### Description of the problem

On creating server my first goal is optimization, `gameFocusChange` event add dynamical stop any functions for more fps on alt+tab.

Exist `isGameFovused` but no fulfills my requirments

### Desired solution for the problem

`gameFocusChange` event for more dynamical stop any event

### Version

10

**Comment by FabianTerhorst** [comment] 2022-02-27 00:31
Duplicate of #1390

**Closed by FabianTerhorst** 2022-02-27 00:31 UTC
Labels: Class: enhancement
