### ISSUE TITLE
Client crash with collision with fuel pump

### ISSUE THREAD

**Issue by stevemqeen** [altmp/altv-issues#877] opened 2021-04-26 00:11 UTC
Steps to reproduce: Take a car (I used custom dlc car) and run over fuel pump, on explosion client crashes.
Server version used: Dev #4.0-dev5 linux

**Comment by LeonMrBonnie** [comment] 2021-04-26 08:56
Duplicate of #861 
Also for next time, please follow the issue template.

**Closed by LeonMrBonnie** 2021-04-26 08:56 UTC
