### ISSUE TITLE
Trailer attachements to vehicles do not work if using vehicle.manualEngineControl on trailer

### ISSUE THREAD

**Issue by edgarasx** [altmp/altv-issues#2189] opened 2024-01-12 14:11 UTC
### Description of the problem

In altv v15 driving up to the trailer would automatically attach the trailer to the vehicle, now it does not work. The issue is caused by toggling vehicle.manualEngineControl (of the trailer). It doesn't matter if you set it to true or false. If you use it atleast once on the trailer it will not automatically attach.

https://github.com/altmp/altv-issues/assets/3003497/818707e2-fdf0-40f2-8054-5a8b03d92aa4

### Reproduction steps

Spawn trailer, set vehicle.manualEngineControl = false and vehicle (which is able to attach a trailer). Attempt to drive up to the trailer.

### Expected behaviour

Should automatically attach the trailer.

### Operating system

Windows 10

### Version

16.0.0-rc.4

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by xxshady** [comment] 2024-01-12 14:12
vehicle.manualEngineControl doesn't work anyway

**Comment by xxshady** [comment] 2024-01-12 14:12
See: https://github.com/altmp/altv-issues/issues/1434

**Comment by FabianTerhorst** [comment] 2024-01-12 14:13
duplicate of #2169

**Closed by FabianTerhorst** 2024-01-12 14:13 UTC
Labels: Class: bug
