### ISSUE TITLE
Vehicle interior bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2225] opened 2024-02-02 18:41 UTC
### Description of the problem

If you teleport a vehicle into a gta v interior with a server-side .pos property while sitting in it, the interior is not loaded. (The getInteriorFromEntity native returns 0.)
If you set the position of the vehicle on the client side with setEntityCoordsNoOffset native, the interior is loaded.
Entitysets are set correctly in all cases.

### Reproduction steps

For example:
vehicle.pos = new alt.Vector3(809.4625854492188, -3003.88330078125, -69.6312713623) -> not loaded

Workaround:
Server-side: vehicle.pos = new alt.Vector3(809.4625854492188, -3003.88330078125, -69.6312713623) -> not loaded
Client-side: game.setEntityCoordsNoOffset(veh.scriptID, 809.4625854492188, -3003.88330078125, -69.631271362, true, true, true); -> loaded

### Expected behaviour

-

### Operating system

Windows 11

### Version

alt:V build #16.0.69, branch release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by xxshady** [comment] 2024-02-02 18:42
Duplicate of https://github.com/altmp/altv-issues/issues/2206?

**Comment by Lekenthu** [comment] 2024-02-02 18:43
> Duplicate of #2206?

Hm, maybe yes.

**Closed** 2024-02-02 18:53 UTC
Labels: Class: bug
