### ISSUE TITLE
Receive key location in keydown Event

### ISSUE THREAD

**Issue by Chapodev** [altmp/altv-issues#1387] opened 2022-02-23 19:12 UTC
### Description of the problem

Currently we dont receive a "location" Parameter in the Client keydown Event.
The keycodes are the same, e.g. for left Ctrl and right Ctrl.
We'd need the key location to decide between left or right Ctrl / Shift Buttons.

Have a look on the following page, you will see that left Ctrl and right Ctrl will return a different key location.
https://keycode.info/

### Desired solution for the problem

Pass a location parameter to the keydown Event
```
alt.on('keydown', (key, location) => {
      console.log(key);
      console.log(location);
});
```

### Version

release-9.6

**Comment by FabianTerhorst** [comment] 2022-02-23 19:27
Duplicate of #1190

**Closed by FabianTerhorst** 2022-02-23 19:27 UTC
Labels: Class: enhancement
