### ISSUE TITLE
Streaming vehiclelayouts.meta doesn't work

### ISSUE THREAD

**Issue by DamsDams** [altmp/altv-issues#567] opened 2020-06-11 19:39 UTC
vehiclelayouts.meta stream not working
Discord contact if needed : Dams#7829

I'm a modder, 

Working on a new project I have to modify a vehiclelayouts.meta, to modify the number of seats . I created a new layout from a vanilla one, I only add two lines propely. I made tests, the file is correctly created but it seams that it is not stream. Tried to test it on fivem, the file works. When I launch my local server, the vehicle can spawn, I try to go inside, I can't, no animation. When I climb on the vehicle, the game crash. According to other modders I know, it might come from way the vehiclelayouts.meta is stream (not stream). 

Here is what I wrote in my stream.CFG : stream/submarinedrug/vehiclelayouts.meta: VEHICLE_LAYOUTS_FILE

Nothing on the crashdump

**Expected behavior**

I should be able to spawn the vehicle and go inside, that switch from the seat 1 to seat 2.

**Current behavior**

I can spawn the vehicle, can go in it, no animation started, and when I climp on the vehicle the game crash.

**Possible solution**

Maybe there is a problem with the stream, if the file wasn't good but streamed, I should have a start of animation or an instant crash a the moment I try to enter inside the vehicle. 

**Steps to reproduce**

here are files of my project, 

[submarinedrug.zip](https://github.com/altmp/altv-issues/files/4766857/submarinedrug.zip)

add this to your stream.cfg : 

files: [

  stream/submarinedrug/assets/*
]
meta: {
stream/submarinedrug/vehiclelayouts.meta: VEHICLE_LAYOUTS_FILE
stream/submarinedrug/handling.meta: HANDLING_FILE
stream/submarinedrug/vehicles.meta: VEHICLE_METADATA_FILE
stream/submarinedrug/carcols.meta: CARCOLS_FILE
stream/submarinedrug/carvariations.meta: VEHICLE_VARIATION_FILE
}

https://streamable.com/0335n6

**Context (environment)**

**Detailed description**

**Possible implementation**

**Comment by Kmz-rash** [comment] 2020-06-13 06:49
got the same issue, spawned it in the water, tryed to go inside but ped was like stuck

**Comment by kasuganosoras** [comment] 2020-08-07 15:32
Is there any update?

**Comment by ZackaryH8** [comment] 2020-08-09 10:57
I am also having issues of the game just crashing out when I attempt to enter the vehicle. Attached below is my crash dump:

[MiniDump](https://drive.google.com/file/d/1MrmP1mFHpegX5vwrdYsxfMASTn2pmwm4/view?usp=sharing)

**Comment by MiroSHGen** [comment] 2020-09-24 18:39
I confirm that any right-hand drive car causes the game to crash

**Comment by mrgharabaghi** [comment] 2021-09-20 16:16
Any news?

**Comment by mrgharabaghi** [comment] 2021-09-20 17:33
Vehicles are one of the most important things in GTA V RP and, players spend most of their time with vehicles.
In my opinion, after update 6, it's a good time to fix issues like #684, #990, and #567.
Many RPs are done with vehicles and such bugs are very bad.

**Comment by vadzz-dev** [comment] 2021-09-21 00:23
Can confirm that issue, the problem is vehiclelayouts should be loaded before vehicles.meta. So we need to handle that in core, as a temp workaround you can put vehiclelayouts into its own resource and set it as a dependency for all your vehicles

**Comment by mrgharabaghi** [comment] 2021-09-21 06:51
> as a temp workaround you can put vehiclelayouts into its own resource and set it as a dependency for all your vehicles

It doesn't work and the game crashed.

**Comment by vanlueckn** [comment] 2022-07-29 23:27
Is there any update on this?

**Comment by C0kkie** [comment] 2023-03-02 16:39
Should be fixed since dev/14.0-dev52

**Closed by C0kkie** 2023-03-02 16:39 UTC
Labels: Class: bug, Side: client, Status: confirmed, Scope: native
