### ISSUE TITLE
Cef crash

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#768] opened 2020-12-22 22:51 UTC
**Client/server version**
`Build rc/2.2-rc12`

**Current behavior**
I crash if I click on a CEF button which makes the cursor to be selection cursor.
(Picture: https://i.imgur.com/um3AD93.png)

**Expected behavior**
Crash fix. It works perfectly with the current release version.

**Steps to reproduce**
https://pastebin.com/WxtdBjst

**Context (environment)**
-

**Possible solution**
-

**Comment by 7Hazard** [comment] 2020-12-22 22:58
Cannot be confirmed, please provide sample code or this issue will be closed.

**Comment by Lekenthu** [comment] 2020-12-22 23:07
I use Sweetalert, so I thought it doesn't make sense linking it. Althought I have written another example that causes the bug to happen: https://pastebin.com/WxtdBjst. 
I also have crashdump: https://www.upload.ee/files/12675441/altv_2.2-rc12_Steam_0x66d9c0b75_23-12-2020_00-04-57.zip.html

**Comment by LeonMrBonnie** [comment] 2020-12-22 23:37
I tried with the exact code you posted, still works as intended.

**Comment by 7Hazard** [comment] 2020-12-23 09:06
Fixed in latest rc

**Closed by 7Hazard** 2020-12-23 09:06 UTC
Labels: Class: bug
