### ISSUE TITLE
iframe doesnt pass Passwords

### ISSUE THREAD

**Issue by Bubbledev86** [altmp/altv-issues#1801] opened 2023-04-04 11:55 UTC
### Description of the problem

Bevor Version 14 we can login to sngine(lifeinvader) via Phone that calls a URL. After Version 14 we see the URL to login in, but the login doesnt work anymore. From a Normal Browser it works. Seems that the Credential doesnt get passed. So we can put the Credentials but after we click on login we return on the login Page.  Was something edited in the cef that not pass anymore Passwords ?

### Reproduction steps

Have done Test with Version 14.0 / 14.1 /14.2 and 14/3 

### Expected behaviour

After the URL on the phone is open to login with the Credentials. 

### Operating system

Debian 11

### Version

14.0 / 14.1 / 14.2 / 14.3

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by Letsion** [comment] 2023-04-06 05:19
Please add an example code, because it is so hard to understand the error properly. See reproduction steps.

I found a new Bug with Iframes in Chromium on Version 108. The Issue was fixed on 20. December 2022. Idk when the cef latest updated in altV?

Link to Issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1395079&q=dropdown&can=2

**Comment by C0kkie** [comment] 2023-04-06 17:50
You should configure your CORS correctly

**Comment by Bubbledev86** [comment] 2023-04-07 18:50
I try to check the CORS later. What i can´t explain in V13 it works normaly from tablet or Phone since V14  nothing

**Comment by KingMarcel** [comment] 2023-04-13 10:57
Do you use Cookies to store f.ex. an sessionid after the user logs in? @Bubbledev86

**Comment by C0kkie** [comment] 2023-04-16 09:42
Use SameSite none value for cookie settings

**Closed by C0kkie** 2023-04-16 09:42 UTC
Labels: Class: bug
