### ISSUE TITLE
streamSyncedMetaChange it's dispatch before gameEntityCreate

### ISSUE THREAD

**Issue by S0P4** [altmp/altv-issues#1838] opened 2023-05-12 12:38 UTC
### Description of the problem

On a entity re-stream, streamSyncedMetaChange get dispatch before gameEntiryCreate, so in the streamSyncedMetaChange  event, the entity scriptID will be 0 and make imposible to use natives whit it. 

### Reproduction steps

Clienside 
```ts
alt.on("streamSyncedMetaChange", (entity: alt.Entity, key: string, value: string[]) => {
    console.log(entity.scriptID)
});
```

Serverside

Create some vehicle, set it a streamSyncedMeta and go away from it to mate it de stream. After that go back to the 

### Expected behaviour

I was specting that `streamSyncedMetaChange` will have a valid script id to make easy the data sync process.

### Operating system

Windows 11

### Version

dev/15.0-dev125

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment] 2023-05-12 12:39
Should be duplicate of #1398

**Closed by C0kkie** 2023-05-12 12:39 UTC
Labels: Class: bug
