### ISSUE TITLE
server-side SetHeadOverlay overlay id 3 not working

### ISSUE THREAD

**Issue by MosIbOad** [altmp/altv-issues#2136] opened 2023-11-29 11:27 UTC
### Description of the problem

C# Server-side overlay id 3 is not working. Client side native is working

### Reproduction steps

```
[Command("overlay")]
public static void COM_SetOverlay(PlayerModel player)
{
    player.SetHeadOverlay(3, 14, 1f);
}
```

### Expected behaviour

There may be a problem with the Server-Side SetHeadOverlay function. Because it works on the client side.

### Operating system

Windows 11

### Version

release / 15.62

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment] 2023-11-29 11:34
You selected that you have tested it on dev. On which dev version did you tested it?

**Comment by MosIbOad** [comment] 2023-11-29 11:38
The problem is in the release version. I wanted to report it for the release version.

**Comment by BluePeer** [comment] 2023-11-29 13:01
for release it is still a Open Issue from Pre 15
https://github.com/altmp/altv-issues/issues/1811

**Comment by xxshady** [comment] 2023-12-29 12:26
duplicate of #1811

**Closed by xxshady** 2023-12-29 12:26 UTC
Labels: Class: bug
