### ISSUE TITLE
Add Marker API in Server-Side

### ISSUE THREAD

**Issue by Whitee303** [altmp/altv-issues#1574] opened 2022-07-26 19:37 UTC
### Description of the problem

In my opinion, adding a Marker API on the server side would make life easier. Since it was earlier in Roadmap 9.0 (probably), why wasn't it implemented? I don't really understand some of these decisions.

### Desired solution for the problem

`const  my_useless_marker = new alt.Marker(type, x,y,z scale,options:{direction,rotation,color,visible,dimension})`

### Additional context

Read and reflect on this request

**Comment by FabianTerhorst** [comment] 2022-07-26 19:38
Duplicate of #128

**Closed by FabianTerhorst** 2022-07-26 19:38 UTC
Labels: Class: enhancement
