### ISSUE TITLE
Throwables  (Snowball, Baseball, Grenade, ...) and Projectiles (RPG, Grenade Launcher, ...)

### ISSUE THREAD

**Issue by TeubyDE** [altmp/altv-issues#1219] opened 2021-11-25 18:18 UTC
### Description of the problem

Throwables and Projectiles are not sync for other Players. Only the throwing / firing Player can see it flying. 
All other Players will only see the effect (explosion of grenade , fire of molotov cocktail, gas from BZ gas,...)

This is tested and reproduced in Version release/6.4 and rc/7.0-rc4. 
On Debian 10 Server Side and Windows Version 10.0.19042 Build 19042Client Side

### Reproduction steps

1. Setup a server and run the example freeroam resource.
2. Join it with at least 2 players.
3. Throw/Fire one of the following example weapons.
- weapon_ball
- weapon_bzgas
- weapon_flare
- weapon_grenade
- weapon_molotov
- weapon_pipebomb
- weapon_proxmine
- weapon_smokegrenade
- weapon_snowball
- weapon_stickybomb
- weapon_rpg
- weapon_grenadelauncher
- weapon_grenadelauncher_smoke
- weapon_hominglauncher
- weapon_firework
- weapon_compactlauncher
- weapon_raypistol
- weapon_flaregun

### Expected behaviour

Throwables and Projectiles are visible/sync for all Players. Not only for the throwing / firing Player.

### Operating system

Debian 10 / Windows 10

### Version

release/6.4 and rc/7.0-rc4

**Comment by juztim** [comment] 2021-11-25 18:29
Duplicate of 
https://github.com/altmp/altv-issues/issues/660

**Comment by juztim** [comment] 2021-11-25 18:29
Also please always test on dev branch

**Comment by TeubyDE** [comment] 2021-11-25 18:31
> Duplicate of #660

kinde of, but there i much more affected then just the stickybomb and the proximitymine.
Could have simmilary reasons why its broken.

i will test it on DEV.

**Closed** 2021-11-25 18:31 UTC
Labels: Class: bug

**Comment by ThomasMarangoni** [comment] 2021-11-25 18:38
Please add new information to #660

**Comment by TeubyDE** [comment] 2021-11-25 18:44
Tested in dev/7.0-dev20 broken as well.
