### ISSUE TITLE
Resource case-sensitivity lets the client crash

### ISSUE THREAD

**Issue by RealNenzar** [altmp/altv-issues#807] opened 2021-01-15 16:30 UTC
**Client/server version**
2.8 Release / 2.8 Release

**Current behavior**
As soon as a folder in the resources folder starts with a capital letter
The client crashes on connect without any message and only with a crashdump.
But the server starts normally without errors

**Expected behavior**
The client should connect to the server without problems

**Steps to reproduce**
Rename a resource from "test" to "Test" and the client crashes on connect

**Comment by LeonMrBonnie** [comment] 2021-01-15 16:32
Duplicate of https://github.com/altmp/altv-issues/issues/436

**Closed by LeonMrBonnie** 2021-01-15 16:32 UTC
Labels: Class: bug
