### ISSUE TITLE
WebView load events not firing

### ISSUE THREAD

**Issue by PepoDance** [altmp/altv-issues#477] opened 2020-03-12 18:33 UTC
**Expected behavior**
The dom events from cef should fire, lol.

**Current behavior**
When you use a dom event it needs extra time to fire the event, previously it didn't need any timeout or time to fire the event.

```js
document.addEventListener("DOMContentLoaded", e => {
  const messagesListHeight = settings._MAX_MESSAGES_ON_CHAT * 22,
    chatBoxHeight = messagesListHeight + 50;
  elements.chatBox.style.height = chatBoxHeight + "px";
  elements.chatMessagesList.style.height = messagesListHeight + "px";
  alt.emit("chat:onLoaded");
});
```

**Possible solution**
Without a setTimeout it's not working and you need to either add a setTimeout to the client or cef code to deal with it.

```js
document.addEventListener('DOMContentLoaded', (e) => {
  const messagesListHeight = settings._MAX_MESSAGES_ON_CHAT * 22,
  chatBoxHeight = messagesListHeight + 50;
  elements.chatBox.style.height = chatBoxHeight + "px";
  elements.chatMessagesList.style.height = messagesListHeight + "px";

  setTimeout(() => {
    alt.emit("chat:onLoaded");
  }, 2500);
});
```

**Steps to reproduce**
I don't know steps to reproduce, use a dom event. Maybe @Stuyk or @MacieGx can provide some input on this too. I'm not the only one with the issue.

**Context (environment)**
Events that are using dom events are broken and take a little extra time to fire. They didn't previously need this type of stuff.

**Detailed description**
I think I described it above.

**Comment by FabianTerhorst** [comment] 2020-03-12 18:34
I don't see a dom event in the code snippets you posted.

**Comment by PepoDance** [comment] 2020-03-12 18:40
> I don't see a dom event in the code snippets you posted.

It's not the cef code, it's clientside and my webview code. I updated the issue.

**Comment by MacieGx** [comment] 2020-03-12 18:41
It's just seems like you can receive event from CEF, but can't send it to it on startup. It's definitely issue which should be fixed.

**Comment by Lhoerion** [comment] 2020-03-12 19:03
@MacieGx @PepoDance Event like ``DOMContentLoaded`` or ``load`` are called for me.
```
window.addEventListener("load", () => {
	console.log("Window \"load\" event called at state " + document.readyState);
});
/* Both window and document works in this case */
window.addEventListener("DOMContentLoaded", () => {
	console.log("Window \"DOMContentLoaded\" event called at state " + document.readyState);
});
```

**Comment by MacieGx** [comment] 2020-03-12 19:17
The DOM events are working fine, just send event to client and then reply to view @Lhoerion

**Comment by Lhoerion** [comment] 2020-03-12 19:55
As I said on Discord, still it works without flaw. No timeouts or other things applied.

**Comment by MacieGx** [comment] 2020-03-12 19:57
It would be nice if @PepoDance sent resource to check it out.

**Comment by Lhoerion** [comment] 2020-03-12 19:59
I've tested it on chat resource, that he had me provided

**Comment by MacieGx** [comment] 2020-03-12 20:01
And there was no timeouts?
In this case, the problem must be dependent on other resources, or only occurs when the resource is loaded as deps.

**Comment by PepoDance** [comment] 2020-03-12 20:41
It's built into the gamemode itself, not loaded as a dep.

**Comment by robertnisipeanu** [comment] 2020-03-13 07:18
This also happens sometimes to me with Vue, (sending a ready event on my main vue component's componentDidMount method). It is something that happens rarely. Didn't really knew why, seems like with a small timeout it works great (I would say 85-90% of the time it works without the timeout too).

**Comment by Lhoerion** [comment] 2020-03-13 12:34
@robertnisipeanu 
In Vue,js on mounted function of instance I use
```
this.$nextTick(() => {
    window.alt.emit('ready');
});
```
With that, I've never experienced any missing event calls (yet).

**Comment by Kudze** [comment] 2020-03-31 04:52
I'm experiencing same issue whilst using ReactJS in my WebView. Though for me it doesn't work at all if I dont add setTimeout.

I'm recieving event sent from cef to client, however I'm not recieving a reply event from client to cef.

#pleaseFix

**Comment by FabianTerhorst** [comment] 2020-03-31 08:36
Events from client to webview are only received when the event handler (alt.on) in the webview js got executed.  That can only be the case when you fire your event from webview to client after that block is reachen.

**Comment by Lhoerion** [comment] 2020-03-31 12:07
@Kudze Try `WebView.on(eventName: "load", listener: (...args: any[]) => void);`

**Comment by Kudze** [comment] 2020-04-01 11:24
@Lhoerion from CEF side?

**Comment by Lhoerion** [comment] 2020-04-01 11:37
@Kudze As the syntax suggest, you need to call it from client-side.

**Comment by Kudze** [comment] 2020-04-01 13:56
From "load" event it works fine.

**Comment by Lhoerion** [comment] 2020-07-25 14:08
Using `load` event is the most reliable way to check if WebView has already loaded. Also the said issue couldn't be reproduced.

Issue closed because of the specified reasons.
Feel free to respond back here, if you think that it should be reopened.

**Closed by Lhoerion** 2020-07-25 14:08 UTC
Labels: Class: bug, Scope: cef, Side: client, Status: invalid
