### ISSUE TITLE
 Tattoos become invisible after a few minutes

### ISSUE THREAD

**Issue by Unrelated-V** [altmp/altv-issues#468] opened 2020-03-08 17:26 UTC
The Tattoos become invisible after a few minutes and this for 3-4 Minutes and then the Tattoos are Visible. The Project Royal-RP.pink and Dirty-Gaming.com have this problems https://clips.twitch.tv/SleepyIntelligentParrotBabyRage

**Comment by FabianTerhorst** [comment] 2020-03-08 17:52
Please post Code to reproduce.

**Comment by ehrenlostv** [comment] 2020-03-08 18:13
game.addPedDecorationFromHashes(alt.Player.local.scriptID,parseInt(tattoos.collection), parseInt(tattoos.overlay));

**Comment by DirtyNenzar** [comment] 2020-04-19 10:19
Is there any news yet?

**Comment by lameule123** [comment] 2020-04-25 19:27
I can confirm this bug is present on my server.

**Comment by martonp96** [comment] 2020-04-25 23:46
Is this bug present both on local player and remote players?

**Comment by DirtyNenzar** [comment] 2020-04-29 16:35
Currently on our server, it is so that the tattoos do not disappear in one self but in other players already

**Comment by Benni9323** [comment] 2020-09-17 16:20
I can confirm this Bug. Please fix, issue exists since ma

**Comment by FacesHC** [comment] 2020-09-28 20:20
Just got this bug while creating the tattooshop stuff I can confirm.

**Comment by martonp96** [comment] 2020-11-03 03:19
The latest dev build (dev/2.1-dev7) should fix this issue, please try it and provide feedback if you can.

**Comment by FacesHC** [comment] 2020-11-06 11:19
Wasn't able to reproduce the bug since, so **probably** working

**Comment by martonp96** [comment] 2020-11-06 11:21
Thank you for your feedback.

**Comment by FabianTerhorst** [comment] 2020-12-24 21:59
Some more infos. Make sure you don't have more then 128 decals active at the same time. One way to do this is to limit decals per player by one.

**Comment by Niitsuj** [comment] 2021-03-28 01:32
As soon as someone enters the streamingrange without any decals or tattoos all the other tattoos disappear. 
If the Player applys a tattoo to himself all the other tattoos are visible again

**Comment by SandDanGlokta** [comment] 2021-07-24 23:11
Any news about this bug?

**Comment by FabianTerhorst** [comment] 2023-06-21 08:04
Please test again if its fixed with last release build.

**Comment by SandDanGlokta** [comment] 2023-07-05 15:08
> Please test again if its fixed with last release build.

No. Its still bugging. Overlays (Tattoos) disapear and appear randomly.

**Comment by C0kkie** [comment] 2023-08-08 23:02
Should be fixed in v15, if not reopen after release

**Closed by C0kkie** 2023-08-08 23:02 UTC
Labels: Class: bug, Side: client, Scope: native, Status: to-investigate
