### ISSUE TITLE
setIntoVehicle on server side sometime not working properly

### ISSUE THREAD

**Issue by CENSOR1337** [altmp/altv-issues#1742] opened 2022-12-26 11:33 UTC
### Description of the problem

after the vehicle is created sometimes the ped falls down through the floor
video: https://streamable.com/5vfq3n

### Reproduction steps

1. Create a new vehicle
2. Set the player into the vehicle immediately after that

code 
```ts
chat.registerCmd("car", (player: alt.Player, args: any) => {
    let model = args[0] ? args[0] : "adder";

    try {
        let vehicle = new alt.Vehicle(model, player.pos.x, player.pos.y, player.pos.z, 0, 0, 0);
        player.setIntoVehicle(vehicle, 1);
    } catch (e) {
        chat.send(player, `{ff0000} Vehicle Model {ff9500}${args[0]} {ff0000}does not exist..`);
    }
});
```

### Expected behaviour

Player being set into the vehicle without falling through the floorA player

### Operating system

Windows

### Version

14.0-dev4

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment] 2022-12-26 11:59
Duplicate of #1174

**Closed** 2022-12-26 12:01 UTC
Labels: Class: bug
