### ISSUE TITLE
CDN prevents server from starting

### ISSUE THREAD

**Issue by BigEll89** [altmp/altv-issues#610] opened 2020-08-13 22:19 UTC
**Client/server version**
`Build #1280, branch release`

**Current behavior**
When CDN enabled in server.cfg serve is not starting.
Server start stops right here:
![image](https://user-images.githubusercontent.com/1353200/90192618-95371e00-ddc3-11ea-934c-abe2315d3faf.png)

Console still open, but no further progress even after a decent couple of minutes.

**Expected behavior**
I expected "server started" within console + "connected to masterlist"

**Steps to reproduce**
server.cfg
-> useCdn: true

**Context (environment)**
Windows Server 2019 and 2016.
AltV Build #1280 Branch Release

**Comment by C0kkie** [comment] 2020-08-13 22:28
We can confirm the same problem. But its not always, just sometimes

**Comment by RobDeFlop** [comment] 2020-08-13 22:51
Bug occurs even without CDN on branch 'rc'

**Comment by Benni9323** [comment] 2020-08-14 00:14
Bug happens always on a clean Server (Downloaded from altv.mp). You need to start & stop 5-10 times, to see the "Server started" Message in console, than it works.

**Comment by VictorFerraresi** [comment] 2020-08-14 00:43
For me, it only happens when I try to run the .exe via Command Line. Executing the .exe by doubleclicking it seems to be an alternative meanwhile the fix is beign developed.

**Comment by DiTheRX** [comment] 2020-08-14 11:46
Who found the solution ?

**Comment by C0kkie** [comment] 2020-08-14 11:47
The solution is to wait until the altv devs fixed it

**Comment by DiTheRX** [comment] 2020-08-14 11:51
> The solution is to wait until the altv devs fixed it 
ahahaha

**Comment by gamelaster** [comment] 2020-08-14 13:08
@DiTheRX @C0kkie We already reproduced it and found the problem. It's nothing related to CDN. It will be fixed ASAP.

**Comment by DiTheRX** [comment] 2020-08-14 14:41
> @DiTheRX @C0kkie We already reproduced it and found the problem. It's nothing related to CDN. It will be fixed ASAP.

I love u

**Comment by RobDeFlop** [comment] 2020-08-14 22:15
Issue seems to be solved for me on the latest build on branch 'rc'. Good job guys <3

**Comment by C0kkie** [comment] 2020-08-15 19:51
Jep for me too

**Comment by danilaplee** [comment] 2020-08-16 19:30
doesn't reproduce on linux :)

**Comment by gamelaster** [comment] 2020-08-17 08:44
Looks like it's fixed, if it's still happening, please re-open the issue.
Thanks you all for help.

Closing

**Closed by gamelaster** 2020-08-17 08:44 UTC
Labels: Class: bug, Priority: critical, Side: server, Status: confirmed

**Comment by Lhoerion** [comment] 2020-08-17 16:45
~~Added~~/Fixed/~~Changed~~ in build #[1284](https://discord.com/channels/371265202378899476/528297438348574741/743911884494733407)

Issue closed because of the specified reasons.
Feel free to respond back here, if you think that it should be reopened.
