### ISSUE TITLE
Textlabel colors and new line

### ISSUE THREAD

**Issue by edgarasx** [altmp/altv-issues#2130] opened 2023-11-22 13:54 UTC
### Description of the problem

Currently there is no way of adding line breaks and several colors to the same text label. Unless you create several textlabels with different positions/colors, which is awful.

### Desired solution for the problem

- Add color with either GTA codes https://wiki.rage.mp/index.php?title=Fonts_and_Colors OR custom {#FFFFFF}
- Add line breaks with for example: \n OR ~n~

**Comment by saesrpg** [comment] 2023-11-22 14:13
https://github.com/altmp/altv-issues/issues/1964

**Comment by FabianTerhorst** [comment] 2023-11-22 14:19
As already commented, duplicate of #1964 and #1981
they support <br> after its merged to dev.

**Closed by FabianTerhorst** 2023-11-22 14:19 UTC
Labels: Class: enhancement
