### ISSUE TITLE
Add onPlayerEnterVehicle event.

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#699] opened 2020-11-13 15:31 UTC
**Suggestion**

Add onPlayerEnterVehicle or onPlayerTryToEnterVehicle event (server side)
**Use cases**

Preventing player from entering specific vehicles without using global locks by setting their player.pos, or track vehicle entering attempts or other many using cases.
This can allow people to prevent players from entering vehicles that belong to other gangs, factions, jobs and etc
or even per vehicle // per player vehicle entrance manipulation

**Comment by FabianTerhorst** [comment] 2020-11-13 15:33
Is there a possibility this is a duplicate of #408 ?

**Comment by Heryshaf** [comment] 2020-11-13 15:36
> Is there a possibility this is a duplicate of #408 ?

If his issue aims on detecting pre entering detection then yes, it can be marked as duplicate, couldn't find on searching.
My issue aims on detecting the first instance of `getVehiclePedIsTryingToEnter`

**Comment by Lhoerion** [comment] 2020-11-13 15:36
Duplicate of #408

**Closed by Lhoerion** 2020-11-13 15:36 UTC
Labels: Class: enhancement, Scope: module-api, Side: client, Side: server, Status: duplicate
