### ISSUE TITLE
OnColshape Event not triggered on disconnect/remove

### ISSUE THREAD

**Issue by kineese** [altmp/altv-issues#738] opened 2020-12-09 09:37 UTC
**Client/server version**
`Branch 2.2-rc2 (rc)`
Using C# Server

**Current behavior**
When entering a colshape the OnColShape event gets triggered.
When walking/driving out of a ColShape the event getss triggered.
But the event wont get triggered when disconnecting inside a ColShape or removing a vehicle which is inside a colshape.

**Expected behavior**
OnColshape should be called everytime.

**Steps to reproduce**
Player
1. Create a colshape
2. Walk into colshape
3. Disconnect

Vehicle
1. Create colshape
2. Create Vehicle
3. Drive into colshape
4. Remove vehicle

**Context (environment)**
Using the onColshape feature to track entities inside colshapes as list.

**Possible solution**
Iterate through all colShapes to find the one the entity was inside.

**Comment by C0kkie** [comment] 2020-12-12 18:01
Can you test it in the newest dev-branch @kineese ?

**Comment by martonp96** [comment] 2020-12-12 19:09
how do i reproduce? if i can't reproduce i can't fix it

**Comment by kineese** [comment] 2020-12-13 19:43
I created a C# Async Server resource to test it out: https://github.com/kineese/AltV_PlainServer

**Comment by martonp96** [comment] 2020-12-13 19:51
@kineese the repo is inaccessible

**Comment by kineese** [comment] 2020-12-13 20:06
> @kineese the repo is inaccessible

Sorry VS created it as private repository.. Should work now

**Comment by martonp96** [comment] 2020-12-14 12:16
Fixed in 2.2-dev7

**Closed by martonp96** 2020-12-14 12:16 UTC
Labels: Class: bug, Side: server, Status: to-investigate
