### ISSUE TITLE
Possibility to define size and position of WebView

### ISSUE THREAD

**Issue by TheGodlyLuzer** [altmp/altv-issues#1389] opened 2022-02-24 20:12 UTC
### Description of the problem

It would be really nice to have the possibility to resize a WebView. 
I'm thinking about height, width and position.

This would open new possibilities to use websites as CEF, but not in fullscreen.

### Desired solution for the problem

Add a width, height and position setter to webView.

**Comment by LeonMrBonnie** [comment] 2022-02-24 20:16
Duplicate of #862

**Closed by LeonMrBonnie** 2022-02-24 20:16 UTC
Labels: Class: enhancement
