### ISSUE TITLE
Discord OAuth. Failed to get OAuth2 token second time

### ISSUE THREAD

**Issue by JustCup** [altmp/altv-issues#1471] opened 2022-05-10 18:13 UTC
### Description of the problem

When I re-obtained the token via `requestOAuth2Token()` I get the error
```
[Error] Error: Failed to get OAuth2 token
```
I tried both with reconnect and simply by calling the method a second time.

### Reproduction steps

- Get a token for the first time
- Deauthorise app in discord
- Try to get the token a second time

### Expected behaviour

Same as the first login attempt

### Operating system

Windows 11

### Version

dev/10.0-dev21

**Comment by vicelo23** [comment] 2022-05-13 10:34
I can confirm this problem, I don't know if it is a problem with Discord itself because it happens if you Deauthorize your application.

**Comment by deluvas1911** [comment] 2022-05-22 13:12
Confirmed when using reconnect.
If alt:V get's restarted the Discord popup to authorize the app will be shown again

**Comment by deluvas1911** [comment] 2022-05-22 14:26
Will be fixed with the next update

**Closed by deluvas1911** 2022-05-22 14:26 UTC
Labels: Class: bug, Side: client, Status: fixed

**Comment by b2soft** [comment] 2022-06-24 09:46
Not fixed in 11.0-dev24, please reopen @deluvas1911

**Comment by Firjens** [comment] 2022-09-11 11:55
This issue still occurs with the exact same repro steps.

**Comment by NeekoDev** [comment] 2024-03-02 09:27
Hi, got the same problem on C# (latest nuget package version), server version 16.0.125 (release) and client 16.0.139
