### ISSUE TITLE
the new DLC vehicle bins do not work on release; on C# it works neither on release nor on DEV

### ISSUE THREAD

**Issue by Letsion** [altmp/altv-issues#1071] opened 2021-08-20 18:34 UTC
**Client/server version**
`6.0-dev7 (dev)` and `release 5.4` 

**Current behavior**
the  new vehicles does not work when spawning them under release (JS) and with C# it does not work under all branches.

**Steps to reproduce**
spawn the Vehicle `comet6`

**Comment by FabianTerhorst** [comment] 2021-08-20 18:40
Duplicate of #1015

**Closed by FabianTerhorst** 2021-08-20 18:40 UTC
Labels: Class: bug

**Comment by Letsion** [comment] 2021-08-20 18:44
the last binaries were posted on 27th July and is still like that. This issue request that i opened descripes bit more branches with witch languages it is not working. I don't think it is allmost a duplicate

**Comment by deluvas1911** [comment] 2021-08-20 18:45
@Letsion Please update the original post that you're using the vehicles.bin from #snippets, else it's confusing

**Comment by FabianTerhorst** [comment] 2021-08-20 18:46
There is No difference between the languages. For Code questions ask on discord.

**Comment by Letsion** [comment] 2021-08-20 18:50
For me is not working with C# in the Dev version when i spawn the new vehicles  with the binaries of the snippets where the new dlc vehicles are inside. With Javascript it is working i do not know why but it is working on the dev version and on release then again not.
