### ISSUE TITLE
SyncedMeta not synced to Player on Connect

### ISSUE THREAD

**Issue by DanielSchuech** [altmp/altv-issues#1474] opened 2022-05-11 19:36 UTC
### Description of the problem

The synced meta data is not available on client side when the meta was set before the client connected. 

It is working as expected when `setSyncedMeta` is called on serverside when the player is connected. But it is missing when the player reconnects.

This issue seems to be introduced in `10.0-rc1` since it is no problem in the current release branch.

### Reproduction steps

- call `setSyncedMeta` on vehicle (on serverside)
- connect afterwards
- try `getSyncedMeta` on same vehicle (on clientside)

### Expected behaviour

Synced Meta is available after connecting for any entity

### Operating system

Ubuntu 22.04 LTS

### Version

rc/10.0-1

**Comment by DanielSchuech** [comment] 2022-05-12 13:57
It is no duplicate of https://github.com/altmp/altv-issues/issues/1356 . We experienced some of the issues of 1356 as well in the release branch but i ve currently no reproduction for that issue :(

In `rc/10.0-1` the synced meta data is missing on every connect of the player.

**Comment by FabianTerhorst** [comment] 2022-05-12 15:58
this is not the same bug.

**Comment by deluvas1911** [comment] 2022-05-20 17:43
@DanielSchuech can you provider further information, e.g. what data types you used?
@YannBcf and I aren't able to reproduce the issue

**Comment by DanielSchuech** [comment] 2022-05-20 17:49
I set an id as string on serverside `vehicle.setSyncedMeta('internalId',  'someId');`

and I am trying to request it on serverside `localPlayer.vehicle.getSyncedMeta('internalId')`;

It is undefined on clientside when the player connects after the Synced Meta was set.

**Comment by deluvas1911** [comment] 2022-05-20 20:07
Further remarks:
- the problem is definitely only found when using linux as os
- it only occurs if multiple syncedMeta are set to a vehicle

**Comment by DanielSchuech** [comment] 2022-05-20 20:30
As an addition: This issue exists especially when using Booleans as value: `vehicle.setSyncedMeta('abcde', true)`

**Comment by C0kkie** [comment] 2022-05-21 10:53
Fixed in release/10.1

**Closed by C0kkie** 2022-05-21 10:53 UTC
Labels: Class: bug, Side: server, Status: confirmed, Scope: internal
