### ISSUE TITLE
Cancel button freezes game window

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#2042] opened 2023-10-01 21:50 UTC
### Description of the problem

![изображение](https://github.com/altmp/altv-issues/assets/54737754/fb955f6e-4586-4e39-b89c-621b8a5d2fd5)

### Reproduction steps

1. Connect to server
2. Press the cancel button at the resource download stage
3. If it did not freeze press it again

### Expected behaviour

/

### Operating system

Windows 11

### Version

15.0-dev719

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment] 2023-10-01 23:01
Works fine for me but cancel button redirects to settings page

**Comment by xxshady** [comment] 2023-10-03 08:35
@litolax i'm able to reproduce it every time, try to make one big client resource, setup it to remote server or localhost and connect via remote adress

**Comment by litolax** [comment] 2023-10-03 20:11
Yes, reproduced with 1.88gb of resources

**Comment by martonp96** [comment] 2023-10-04 00:49
Can't reproduce either and yes it sends me back to settings page too

**Comment by martonp96** [comment] 2023-10-04 12:23
Fixed in dev735

**Closed by martonp96** 2023-10-04 12:23 UTC
Labels: Class: bug, Status: confirmed
