### ISSUE TITLE
onClient doesn’t work

### ISSUE THREAD

**Issue by hookmethods** [altmp/altv-issues#2358] opened 2024-10-26 19:07 UTC
### Description of the problem

onClient doesn’t work
emitServer(Raw) doesn’t work 

 AltV related events work
 alt.emit works (client and server)

I’ve tried with freeroam resource I just downloaded from website, they don’t work

### Reproduction steps

Emitting a custom server events from client

### Expected behaviour

It should work

### Operating system

Windows 11

### Version

16.2.15 release 

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by GVMP** [comment] 2024-10-27 17:56
Without code, no reproducing.

Works for me here.

**Comment by Doxoh** [comment] 2024-10-28 11:17
Please add logs and resources to repo it.

Most servers with >100 players didnt have problems.

Otherwise issue will closed in 2 days

**Closed as completed** 2024-10-31 18:23 UTC
Labels: Class: bug

**Comment by woozievert** [comment] 2024-11-07 06:14
I have this problem too.

web: 
```
alt.emit('emitServerEvent', 'login:attempt', this.state.loginForm.username, this.state.loginForm.password, this.state.loginForm.rememberMe);`
```
client:
```
this.browser.on('emitServerEvent', (name: string, ...args: any[]) => {
    alt.logDebug(`emitServerEvent: ${name}, ${args}`); // triggered
    alt.emitServer(name, ...args);
});
```
server:
```
alt.onClient('login:attempt', this.loginAttempt.bind(this));
async loginAttempt(player: alt.Player, username: string, password: string, remember: boolean): Promise<void> {
alt.log('login Attempt triggered'); // not triggered
```
emitServer broken when I upgrade server to latest
16.2.8 -> 16.2.19
server onClient cannot receive
