### ISSUE TITLE
Player SetClothes method works wrong for Masks on female model

### ISSUE THREAD

**Issue by b2soft** [altmp/altv-issues#977] opened 2021-06-21 16:10 UTC
**Client/server version**

`alt:V Server 4.0-dev13, branch dev`

**Current behavior**
Server-side setter SetClothes works not as expected when setting empty mask on a female model using
`player.SetClothes(1, 0, 0, 2);`
![image](https://user-images.githubusercontent.com/6034932/122793277-ad20dd80-d2c3-11eb-86ac-d1b18584892c.png)
_Actually it sets drawableId == 27 mask_

when setting the same mask using a native `native.setPedComponentVariation(alt.Player.local.scriptID, 1, 0, 0, 2);` result is as expected:
![image](https://user-images.githubusercontent.com/6034932/122793361-c75abb80-d2c3-11eb-8c88-395a937ac282.png)

All other Mask IDs work OK.

Reference used: https://wiki.rage.mp/index.php?title=Masks and https://forge.plebmasters.de/clothes/MzIxMjc1MzAxNQ

**Expected behavior**
Correct empty mask is set using server-side setter

**Steps to reproduce**
1. Set player model to Female Freemode 01
2. Call `player.SetClothes(1, 0, 0, 2);`
3. Mask is incorrect

**Context (environment)**
Trying to set masks servderside

**Possible solution**
Use native to set a mask on the client-side

**Comment by C0kkie** [comment] 2021-06-21 16:30
Is it only for female or also for male?

**Comment by deluvas1911** [comment] 2021-06-21 16:32
Can confirm this behaviour on 4.0-dev13.
Same occurs with component 9 (body armor)
![GTA5_WPnfBJgBBr](https://user-images.githubusercontent.com/69921315/122796715-ffabcb00-d2be-11eb-9b15-7a5c6fd6d17b.png)

@C0kkie no issues with male

**Comment by b2soft** [comment] 2021-06-21 16:34
> 
> 
> Is it only for female or also for male?

Only for Female. Male works as intended for what I've tested.

**Comment by C0kkie** [comment] 2021-06-21 16:35
Just mask and body armor or something else too?

**Comment by deluvas1911** [comment] 2021-06-21 16:41
Just double checked. If I spawn an "naked" female ped with following components:
| Component | Drawable |
| --- | --- |
| 3 | 15 |
| 4 | 15 |
| 6 | 35 |
| 8 | 15 |
| 11 | 15 |

And set by server all unused component ids to drawable 0 texture 0 (e.g. on respawn), I have to remove by native: 1 (Mask) 7 (Accessories) and 9 (Body Armor)

**Comment by b2soft** [comment] 2021-06-21 16:43
> 
> 
> Just mask and body armor or something else too?

I've tested for legs, torso, hats, watches, hats - they are ok.  I have issues only with mask drawable = 0

**Comment by b2soft** [comment] 2021-06-21 16:48
Confirmed that body armor is a problem too. Seems drawable ==0 and texture == 0 cause the problem

**Comment by Revyn112** [comment] 2021-06-21 19:17
can also confirm this behaviour on female on 4.0dev-rc1.
This componets get also set by default:

7 - accessory
9 - armour
10 - decal

![grafik](https://user-images.githubusercontent.com/7781906/122815655-085bcb80-d2d6-11eb-8d7b-bdc5dd8615ac.png)

**Comment by FabianTerhorst** [comment] 2021-06-21 21:37
cant reproduce player.SetClothes(1, 0, 0, 2); doesnt show me a mask with female model. Make sure your data files are updated.

**Comment by b2soft** [comment] 2021-06-21 21:41
> cant reproduce player.SetClothes(1, 0, 0, 2); doesnt show me a mask with female model. Make sure your data files are updated.

I downloaded server dev files right at the moment of posting this issue to exclude the problem of the old data. And server is 4.0dev-13, is there any newer version?

**Comment by FabianTerhorst** [comment] 2021-06-21 21:42
no, i dont think so.

**Comment by b2soft** [comment] 2021-06-21 21:46
> no, i dont think so.

I can provide any additional info if needed

**Comment by deluvas1911** [comment] 2021-06-22 05:52
Tested with JS serverside (because @b2soft and I use C#) and issue exists there too

**Comment by yoranjj** [comment] 2021-06-23 11:42
Could you try reproducing the bug with this file? Just replace the current one in the /data/ folder.

[clothes.bin.zip](https://github.com/altmp/altv-issues/files/6701518/clothes.bin.zip)

**Comment by deluvas1911** [comment] 2021-06-23 12:23
Setting component 1 2 7 9 10 to 0 with @yoranjj clothes.bin works fine

**Comment by C0kkie** [comment] 2021-06-24 00:23
Clothes.bin got updated on cdn, just redownload and it will be fixed

**Closed by C0kkie** 2021-06-24 00:23 UTC
Labels: Class: bug, Side: server, Status: to-investigate
