### ISSUE TITLE
Webview flickering after destroying another one

### ISSUE THREAD

**Issue by Konders** [altmp/altv-issues#1113] opened 2021-09-14 11:59 UTC
**Client/server version**

`rc/6.0-rc10, dev/7.0-dev1`

**Current behavior**
If I create one webview, destroy it, create another one or the same webview - on calling the new one constructor, its renders the last one image of destroyed webview, destroy it and then successfully renders our newly created webview, so we have flickering with cached previous page

**Expected behavior**
Webview correctly render page after calling constructor

**Steps to reproduce**
Create first one webview
Destroy first one webview
Create second one webview//on this moment its render first one view, clears that(gotta flick) and then renders our second webview

[Reproduction video](https://www.youtube.com/watch?v=a9jdTJNCz1o)
Resource which can help you to reproduce this bug 
[example.zip](https://github.com/altmp/altv-issues/files/7161636/example.zip)
Usage: press E, press again E, press R, press again R, press E, press E

**Context (environment)**
After update to rc/dev branch all our webview are flickering on their create step, on release its works fine

**Possible solution**
idk, I think that there is some memory leak, because its open cached page which must be already destroyed

**Comment by Konders** [comment] 2021-09-14 12:21
p.s
This bug has been confirmed from 3 different pc

**Comment by deluvas1911** [comment] 2021-09-15 11:51
Confirmed. Guess it's related to #1096

**Comment by C0kkie** [comment] 2021-09-17 02:22
@deluvas1911 @Konders  Should be fixed in rc/6.0-rc12, please report back if its fixed for you

**Comment by Konders** [comment] 2021-09-17 06:22
Server and client -> rc/6.0-rc13
still can confirm that issue

**Comment by deluvas1911** [comment] 2021-09-27 20:14
Unable to reproduce with rc16

**Comment by Konders** [comment] 2021-09-28 06:34
Still can reproduce it with rc16 and attached resource example&&production code

**Comment by Konders** [comment] 2021-09-28 06:40
https://user-images.githubusercontent.com/29742102/135035998-2c5b999e-06aa-4375-ad79-277cfc014443.mp4

reproduction proof

**Comment by martonp96** [comment] 2021-09-28 08:30
@Konders did you get any error in the F8 console?

**Comment by Konders** [comment] 2021-09-28 08:52
> @Konders did you get any error in the F8 console?

No, I even doesn't have any warnings

**Comment by Konders** [comment] 2021-09-28 12:17
> @Konders do you have any other resources on test server? Can't really reproduce it with only this resource enabled

Give me some time, I'll provide you second sample resource for reproducing that

**Comment by Konders** [comment] 2021-09-28 14:29
[example2.zip](https://github.com/altmp/altv-issues/files/7244933/example2.zip)
Usage: 
enter vehicle
leave vehicle(sometimes flick)
close inventory
enter vehicle(flick)

**Comment by Konders** [comment] 2021-09-28 16:42
tested on intel processor with two rx580 - sometimes this bug reproducing, but with 40% chance
on two pc with ryzen 5 3400g reproducing with 100% chance

**Comment by vadzz-dev** [comment] 2021-09-28 16:54
That's something really weird, entered vehicle with your resource like 20 times and no flicks :/

**Comment by Konders** [comment] 2021-09-28 16:57
https://user-images.githubusercontent.com/29742102/135131864-36ac833d-ec3b-402f-ba85-53d11600fa15.mp4

Reproduction of one moment(when its flicking)
Also exists second moment(when you creating new view, its loads previous view, removes it, and only after that things its show real view which I need)

**Comment by Konders** [comment] 2021-09-28 17:09
https://user-images.githubusercontent.com/29742102/135133450-b0d861eb-106a-49d2-a344-599865d667af.mp4

Second moment which I mentioned in previous post

**Comment by Konders** [comment] 2021-09-29 09:02
Ryzen 5 3400g + vega 11 -> 30 iterations of reproducing -> 30 success
i5 + two rx580 -> 30 iterations of reproducing -> 5 success
i7 4700 + GT755m -> 30 iterations of reproducing -> 1 success

**Comment by Konders** [comment] 2021-09-29 09:07
Also on all pc where we reproduce this bug, after every success reproduction cef.log appends some lines
`[0813/120218.786:ERROR:widevine_loader.cc(383)] Widevine CDM registration failed; Missing file D:\AltV\cef\widevine\widevinecdm.dll
[0813/121041.201:ERROR:widevine_loader.cc(383)] Widevine CDM registration failed; Missing file D:\AltV\cef\widevine\widevinecdm.dll
[0825/111958.103:ERROR:widevine_loader.cc(383)] Widevine CDM registration failed; Missing file D:\AltV\cef\widevine\widevinecdm.dll
[0929/115243.785:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0929/115747.257:ERROR:broker_win.cc(56)] Error reading broker pipe: Канал был закрыт. (0x6D)`

**Comment by Konders** [comment] 2021-10-02 10:59
release 6.1, problem still exists

**Comment by Konders** [comment] 2021-10-06 09:40
7.0-dev5: still can reproduce

**Comment by YannBcf** [comment] 2022-03-11 00:30
@Konders Can you still reproduce it on release ?

**Comment by YannBcf** [comment] 2022-05-15 15:45
If the issue still happen feel free to reopen it

**Closed by YannBcf** 2022-05-15 15:45 UTC
Labels: Class: bug, Scope: webview
