### ISSUE TITLE
Health and armor of streamedin players are set to the health/armor of the current player on streamin

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1097] opened 2021-09-09 16:11 UTC
**Client/server version**
Latest release 5.3

**Current behavior**
We have a system for health/armor bars. When looping through alt.Player.streamedIn we use the client-side health/armor getter.
The problem is, as soon as a player streams in their INITIAL health is set to the current player's health(aka alt.Player.local).
When shooting the player once it resets to their actual health etc.

**Expected behavior**
Health/armor should be the other player's health/armor upon streamin.

**Steps to reproduce**
- Damage yourself
- Teleport another player to you(that wasnt streamed in yet)
- The other player has same health/armor as you, even though on their screen they have different health/armor

Some code to help test.
```
alt.everyTick( ( ) => {
    for( let target of alt.Player.streamedIn )
    {
        alt.log( `target HP ${ target.health } armor: ${ target.armor }` );
    }
} );
```

**Context (environment)**
Health bars show inaccurate health/armor.

**Possible solution**

**Comment by C0kkie** [comment] 2021-09-09 16:15
Can you try if its also with alt.Player.all? I think i noticed the same bug

**Comment by DasNiels** [comment] 2021-09-09 16:17
> Can you try if its also with alt.Player.all? I think i noticed the same bug

Yeah we tried that before, 95% sure it yielded same results.

**Comment by DasNiels** [comment] 2021-09-09 16:20
UPDATE: Current workaround is to use natives.

https://natives.altv.mp/#/0x9483AF821605B1D8
https://natives.altv.mp/#/0xEEF059FAD016D209

**Comment by LeonMrBonnie** [comment] 2022-01-09 06:18
It seems like this issue was already fixed in the past, as the issue is not present anymore

**Closed by LeonMrBonnie** 2022-01-09 06:18 UTC
Labels: Class: bug, Side: client, Status: confirmed, Scope: internal
