### ISSUE TITLE
[JS / Client] drawMarker causes flickering CEF elements

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#827] opened 2021-01-30 22:01 UTC
**Client/server version**
`Build #2.8, branch release`

**Current behavior**
When looking at Marker drawn with the native drawMarker causes flickering CEF - Elements.

**Expected behavior**
CEF shouldn't flickering.

**Steps to reproduce**
```
alt.everyTick(() => {
    natives.drawMarker(
        3,
        0,
        0,
        72,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        255,
        255,
        255,
        255,
        false,
        false,
        2,
        false,
        undefined,
        undefined,
        false
    );
});
```

Example of the issue is shown here: https://streamable.com/kxel7j

**Comment by FabianTerhorst** [comment] 2021-01-30 22:02
Call drawRect(0, 0, 0, 0, 0, 0, 0, 0, 0) in every tick. Its a know gta bug.

**Comment by FabianTerhorst** [comment] 2021-01-30 22:02
Duplicate of #644

**Closed by FabianTerhorst** 2021-01-30 22:02 UTC
Labels: Class: bug
