### ISSUE TITLE
toggleGameControls lock fire control

### ISSUE THREAD

**Issue by Arochka** [altmp/altv-issues#998] opened 2021-07-07 15:21 UTC
**Client/server version**
`release 2.23`

**Current behavior**
The attack control is locked and fire continuously

**Expected behavior**
The control should be cancelled and player should not fire continuously

**Steps to reproduce**
`
alt.everyTick(() => {
  if (native.isControlJustPressed(0, 24)) {
    alt.log('Attack Pressed')
    alt.toggleGameControls(false)
  }
})
`

**Context (environment)**
I'm disabling game controls when player focus an input in a webview, that allow us for example with a phone, for example to continue walking in the street with it but when they focus an input I disable controls, and when they blur input they can continue doing what they want.
The problem is that if they have a weapon equiped it start fireing like hell

**Comment by LeonMrBonnie** [comment] 2021-07-07 15:22
Duplicate of #808

**Closed by LeonMrBonnie** 2021-07-07 15:22 UTC
Labels: Class: bug
