### ISSUE TITLE
Players Alpha gets resetted to 255 when leaving a vehicle

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1073] opened 2021-08-22 12:57 UTC
**Client/server version**

Release 5.4

**Current behavior**
When applying a new alpha to the player, and then leaving a vehicle, the alpha gets resetted to 255.

**Expected behavior**
Alpha shouldn't change when leaving a vehicle.

**Steps to reproduce**
- Spawn a vehicle
- Apply eg. alpha 125 to the player in clientside
- enter the vehicle
- leave the vehicle

**Possible solution**
Currently I need to set the alpha back to 125 when the player left a vehicle

**Attachments**

https://user-images.githubusercontent.com/50775241/130356152-5d5bbe73-fd20-402e-b018-a101ec989549.mp4

**Comment by LeonMrBonnie** [comment] 2021-08-22 13:04
Duplicate of https://github.com/altmp/altv-issues/issues/528

**Closed by LeonMrBonnie** 2021-08-22 13:04 UTC
Labels: Class: bug
