### ISSUE TITLE
Client crash if dependency resource not started manually

### ISSUE THREAD

**Issue by Konders** [altmp/altv-issues#1115] opened 2021-09-15 10:21 UTC
**Client/server version**
`rc/6.0-rc12`

**Current behavior**
When you have any dependencies in resource.cfg, and this dependency resource not started manually or through server.cfg startup, when you connect - your client would be crashed

**Expected behavior**
Dependency resources starts automatically before root resource start, and client do not crash on connect

**Steps to reproduce**
Download release candidate server with all checkboxes on
Remove chat from server.cfg startup
clear client cache(you shouldn't do this step if you connecting to server first time and do not have dependency on startup)
Connect to server

**Comment by deluvas1911** [comment] 2021-09-15 10:33
Neither my server nor my client are crashing when I remove chat from the server.cfg startup. Chat is still loaded from server because it's a dependency of freeroam and client connects just fine.

**Comment by Konders** [comment] 2021-09-15 11:23
> Neither my server nor my client are crashing when I remove chat from the server.cfg startup. Chat is still loaded from server because it's a dependency of freeroam and client connects just fine.

Try to clear client cache, then this bug appears
By default if you connect to your server first time and dependency not started - you will get crash

**Comment by deluvas1911** [comment] 2021-09-15 11:25
Ah right, forget about my client cache.
Issue is confirmed

**Comment by FabianTerhorst** [comment] 2021-09-15 22:28
Can you upload the crashdump?

**Comment by Konders** [comment] 2021-09-16 06:07
[altv_6.0-rc12_Steam_0x1c4bf4ed9_15-09-2021_14-34-40.zip](https://github.com/altmp/altv-issues/files/7175246/altv_6.0-rc12_Steam_0x1c4bf4ed9_15-09-2021_14-34-40.zip)

**Comment by martonp96** [comment] 2021-09-17 12:57
fixed in rc

**Closed by martonp96** 2021-09-17 12:57 UTC
Labels: Class: bug, Side: client, Status: confirmed
