### ISSUE TITLE
Attached vehicles disappear when passing map cell area

### ISSUE THREAD

**Issue by edgarasx** [altmp/altv-issues#2086] opened 2023-10-21 01:41 UTC
### Description of the problem

Attached vehicles (trailers) sometimes disappear, as reported by my players. I could not reproduce the issue myself, but my players figured out that at certain points, where the trailer of the truck disappears, they can return to that point, regain the attached trailer and they can drive in reverse past the same point, and the trailer does not disappear.

To me it seems like it has something to do with the stream map cell area. If the main vehicle (with player inside) passes to another map cell area, everything is fine. But if it has a vehicle attached, than that attached vehicle stays in the previous map cell area. Unless the attached vehicle is the first to pass to another map cell area, before the main vehicle (that it is attached to).

### Reproduction steps

1) Spawn the truck
2) Attach a trailer to it
3) Drive around the map

Video of the issue https://streamable.com/1bsh47

### Expected behaviour

Attached vehicle should not disappear

### Operating system

Debian 11

### Version

15.1

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by edgarasx** [comment] 2023-10-21 16:21
Some more videos of the issue (recorded before release):
https://streamable.com/e8pvz4
https://streamable.com/ag8t79
https://streamable.com/whin3h (2 players inside a truck)

Video (recorded after release) showing how driving in reverse helps keeping the trailer from disappearing:
https://www.youtube.com/watch?v=87KF2fS55P0

**Comment by edgarasx** [comment] 2023-10-21 21:09
We can successfully reproduce the issue on our test server and even collected all related logs, but at the moment of disappearance there are no logs related to the issue.

Video of the event: https://streamable.com/oqtw8i

Full log starting with creation of the truck:
```js
// Truck is created
[23:12:48] [EVENT DEBUG] baseObjectCreate {
  baseObject: 'Vehicle{ id: 61, model: 1518533038, modelString: Hauler, numberPlateText: ALTV, driver: undefined, netOwner: undefined }'
}

// Truck is assigned a netOwner
[23:12:48] [EVENT DEBUG] netOwnerChange {
  entity: 'Vehicle{ id: 61, model: 1518533038, modelString: Hauler, numberPlateText: FURISTAI, driver: undefined, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  owner: 'Player{ id: 1, name: Gugix_Fantix }',
  oldOwner: 'null'
}

// Player enters truck
[23:12:48] [EVENT DEBUG] playerEnteredVehicle {
  player: 'Player{ id: 1, name: Gugix_Fantix }',
  vehicle: 'Vehicle{ id: 61, model: 1518533038, modelString: Hauler, numberPlateText: FURISTAI, driver: Player{ id: 1, name: Gugix_Fantix }, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  seat: 1
}

// Player leaves truck
[23:13:02] [EVENT DEBUG] playerLeftVehicle {
  player: 'Player{ id: 1, name: Gugix_Fantix }',
  vehicle: 'Vehicle{ id: 61, model: 1518533038, modelString: Hauler, numberPlateText: FURISTAI, driver: undefined, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  seat: 1
}

// Trailer is created
[23:13:04] [EVENT DEBUG] baseObjectCreate {
  baseObject: 'Vehicle{ id: 62, model: 2942498482, modelString: trflat, numberPlateText: ALTV, driver: undefined, netOwner: undefined }'
}

// Trailers is asiggned a netOwner
[23:13:04] [EVENT DEBUG] netOwnerChange {
  entity: 'Vehicle{ id: 62, model: 2942498482, modelString: trflat, numberPlateText: LMG5, driver: undefined, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  owner: 'Player{ id: 1, name: Gugix_Fantix }',
  oldOwner: 'null'
}

// Player is entering truck
[23:13:05] [EVENT DEBUG] playerEnteringVehicle {
  player: 'Player{ id: 1, name: Gugix_Fantix }',
  vehicle: 'Vehicle{ id: 61, model: 1518533038, modelString: Hauler, numberPlateText: FURISTAI, driver: undefined, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  seat: 1
}

// Player enters truck
[23:13:08] [EVENT DEBUG] playerEnteredVehicle {
  player: 'Player{ id: 1, name: Gugix_Fantix }',
  vehicle: 'Vehicle{ id: 61, model: 1518533038, modelString: Hauler, numberPlateText: FURISTAI, driver: Player{ id: 1, name: Gugix_Fantix }, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  seat: 1
}

// Trailer is attached to truck
[23:13:12] [EVENT DEBUG] vehicleAttach {
  vehicle: 'Vehicle{ id: 62, model: 2942498482, modelString: trflat, numberPlateText: LMG5, driver: undefined, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  attachedVehicle: 'Vehicle{ id: 61, model: 1518533038, modelString: Hauler, numberPlateText: FURISTAI, driver: Player{ id: 1, name: Gugix_Fantix }, netOwner: Player{ id: 1, name: Gugix_Fantix } }'
}

// Truck is damaged
[23:13:20] [EVENT DEBUG] vehicleDamage {
  vehicle: 'Vehicle{ id: 61, model: 1518533038, modelString: Hauler, numberPlateText: FURISTAI, driver: Player{ id: 1, name: Gugix_Fantix }, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  attacker: 'null',
  bodyHealthDamage: 1,
  additionalBodyHealthDamage: 0,
  engineHealthDamage: 2,
  petrolTankDamage: 0,
  weapon: 0
}

// Truck is damaged
[23:13:20] [EVENT DEBUG] vehicleDamage {
  vehicle: 'Vehicle{ id: 61, model: 1518533038, modelString: Hauler, numberPlateText: FURISTAI, driver: Player{ id: 1, name: Gugix_Fantix }, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  attacker: 'null',
  bodyHealthDamage: 1,
  additionalBodyHealthDamage: 0,
  engineHealthDamage: 1,
  petrolTankDamage: 1,
  weapon: 0
}

// Truck is damaged
[23:13:21] [EVENT DEBUG] vehicleDamage {
  vehicle: 'Vehicle{ id: 61, model: 1518533038, modelString: Hauler, numberPlateText: FURISTAI, driver: Player{ id: 1, name: Gugix_Fantix }, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  attacker: 'null',
  bodyHealthDamage: 1,
  additionalBodyHealthDamage: 0,
  engineHealthDamage: 2,
  petrolTankDamage: 0,
  weapon: 0
}

// Trailer is damaged
[23:14:46] [EVENT DEBUG] vehicleDamage {
  vehicle: 'Vehicle{ id: 62, model: 2942498482, modelString: trflat, numberPlateText: LMG5, driver: undefined, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  attacker: 'null',
  bodyHealthDamage: 1,
  additionalBodyHealthDamage: 0,
  engineHealthDamage: 0,
  petrolTankDamage: 0,
  weapon: 0
}

// Player is assigned as net owner to another vehicle
[23:15:48] [EVENT DEBUG] netOwnerChange {
  entity: 'Vehicle{ id: 56, model: 1392297243, modelString: e63sf, numberPlateText: LMG738, driver: undefined, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  owner: 'Player{ id: 1, name: Gugix_Fantix }',
  oldOwner: 'null'
}

// Player is assigned as net owner to another vehicle
[23:15:58] [EVENT DEBUG] netOwnerChange {
  entity: 'Vehicle{ id: 64, model: 2245688993, modelString: ben17, numberPlateText: BOSS, driver: undefined, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  owner: 'Player{ id: 1, name: Gugix_Fantix }',
  oldOwner: 'null'
}

// Player is assigned as net owner to another vehicle
[23:16:00] [EVENT DEBUG] netOwnerChange {
  entity: 'Vehicle{ id: 60, model: 3437611258, modelString: veto, numberPlateText: LMG856, driver: undefined, netOwner: Player{ id: 1, name: Gugix_Fantix } }',
  owner: 'Player{ id: 1, name: Gugix_Fantix }',
  oldOwner: 'null'
}

// Player is removed as net owner to another vehicle
[23:16:00] [EVENT DEBUG] netOwnerChange {
  entity: 'Vehicle{ id: 56, model: 1392297243, modelString: e63sf, numberPlateText: LMG738, driver: undefined, netOwner: undefined }',
  owner: 'null',
  oldOwner: 'Player{ id: 1, name: Gugix_Fantix }'
}

// Player is removed as net owner to another vehicle
[23:16:09] [EVENT DEBUG] netOwnerChange {
  entity: 'Vehicle{ id: 64, model: 2245688993, modelString: ben17, numberPlateText: BOSS, driver: undefined, netOwner: undefined }',
  owner: 'null',
  oldOwner: 'Player{ id: 1, name: Gugix_Fantix }'
}

// Player is removed as net owner to another vehicle
[23:16:10] [EVENT DEBUG] netOwnerChange {
  entity: 'Vehicle{ id: 60, model: 3437611258, modelString: veto, numberPlateText: LMG856, driver: undefined, netOwner: undefined }',
  owner: 'null',
  oldOwner: 'Player{ id: 1, name: Gugix_Fantix }'
}

// The trailer disappears at around 23:16:18, there are no logs of it being destroyed, removed or netOwner changed

// Player sends a message as seen in the video (Keep in mind there is a 9 seconds difference between server and client time)
[23:16:21] [chat:msg] Gugix_Fantix: swx kesa

// After the message is sent and the driver reverses back to the trailer there aren't any relevant logs to indicate that the trailer was created, attached or netOwner changed
```

**Comment by edgarasx** [comment] 2023-10-21 22:46
Found the issue, reproducable with:

resources/test/server/index.js
```js
import * as alt from "alt-server";

// Vehicles have to be created further from the position of where it disappears.
const truck = new alt.Vehicle("hauler", new alt.Vector3(3510.936279296875, 3792.659423828125, 30.3582763671875), new alt.Vector3(0.037042342126369476, -0.007299668621271849, 1.546033978462219));
const trailer = new alt.Vehicle("trflat", new alt.Vector3(3521.7099609375, 3792, 30.054931640625), new alt.Vector3(0, 0, 1.4347431659698486));

alt.on("playerConnect", (player) => {
  player.model = "u_m_y_mani";
  player.spawn(2029.3582763671875, 6166.404296875, 48.5728759765625, 0);

  truck.pos = new alt.Vector3(2034.25048828125, 6159.52099609375, 48.808837890625);
  truck.rot = new alt.Vector3(-0.02867751754820347, -0.021489787846803665, 0.6182617545127869);

  trailer.pos = new alt.Vector3(2040.09228515625, 6151.55615234375, 49.0615234375);
  trailer.rot = new alt.Vector3(-0.018991244956851006, -0.024314958602190018, 0.6270227432250977);

  player.setIntoVehicle(truck, 1);
});
```

server.toml:
```toml
name = 'alt:V Server'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
gamemode = 'Freeroam'
website = 'example.com'
language = 'en'
description = 'alt:V Sample Server'
modules = ['js-module']
resources = ['test']
debug = true

streamingDistance = 150
migrationDistance = 150

[maxStreaming]
peds = 128
objects = 120
vehicles = 128
entities = 128
```

Increasing streamingDistance seems to fix it, either way I've added the code if you decide to look into it.

**Comment by BluePeer** [comment] 2023-10-21 23:38
https://www.youtube.com/watch?v=OcM5D5ZQQSA

the attaches are not include in the "migration" of the cell like the vehicle
you see in the video that it needs to bring the truck so far in the next cell that the attached is ported with it's position into the new cell then the cross over within this 2 cells works only on the next cell it starts from new
but after 1 Manual transfer from cell1 to cell2 you can drive accross without loosing the attached trailer

**Comment by FabianTerhorst** [comment] 2023-10-22 11:29
cells aren't same size as streaming distance. so thats completely unrelated.

**Comment by FabianTerhorst** [comment] 2023-10-22 11:46
> https://www.youtube.com/watch?v=OcM5D5ZQQSA
> 
> the attaches are not include in the "migration" of the cell like the vehicle you see in the video that it needs to bring the truck so far in the next cell that the attached is ported with it's position into the new cell then the cross over within this 2 cells works only on the next cell it starts from new but after 1 Manual transfer from cell1 to cell2 you can drive accross without loosing the attached trailer
> 
> used the above repro code with this server.toml changes
> 
> streamingDistance = 25 migrationDistance = 25

please post the code you used to log the positions.

**Comment by BluePeer** [comment] 2023-10-22 15:53
> > https://www.youtube.com/watch?v=OcM5D5ZQQSA
> > the attaches are not include in the "migration" of the cell like the vehicle you see in the video that it needs to bring the truck so far in the next cell that the attached is ported with it's position into the new cell then the cross over within this 2 cells works only on the next cell it starts from new but after 1 Manual transfer from cell1 to cell2 you can drive accross without loosing the attached trailer
> > used the above repro code with this server.toml changes
> > streamingDistance = 25 migrationDistance = 25
> 
> please post the code you used to log the positions.

it was a simple intervall
alt.setInterval(() => {
    alt.log("-------------------------------------------------------------------------------");
    alt.log("Player: " + JSON.stringify(player.pos));
    alt.log("Truck: " + JSON.stringify(truck.pos));
    alt.log("Trailer: " + JSON.stringify(trailer.pos));
}, 5000);<

placed inside the connect after the setintovehicle

**Comment by FabianTerhorst** [comment] 2023-10-22 15:54
Client or server side.

**Comment by FabianTerhorst** [comment] 2023-10-22 15:58
Is the distance increasing that the vehicle and trailer is working when you increase streaming distance. And is it decreasing when you decrease streaming distance?

**Comment by BluePeer** [comment] 2023-10-22 16:04
that is server event in the reproduction code so server values (the screen in video is server console)

the first try was stream 125 like in the repo code the area from spawn and cell1 and cell2 (real loction of the despawn) not changed every the same loction with the same distance to hop the trailer from cell1 to cell2

**Comment by BluePeer** [comment] 2023-10-22 16:28
Interesting
the repo code bugs only if the server toml does not contain
mapCellAreaSize = 100 #smaller areas uses more ram and less cpu
with size 25/100 it does not disapear at that point

Was wondering on my server this not happen and start testing the differences

looks like related to the default cell size

stream distance needs to be minimum identical to cell size to prevent this bug

**Comment by FabianTerhorst** [comment] 2023-10-22 18:01
default cell area size is 200

**Comment by BluePeer** [comment] 2023-10-23 11:42
Bug still exist in dev 815
[repo-dev.zip](https://github.com/altmp/altv-issues/files/13069587/repo-dev.zip)
![GTA5_Gdn16S3Tm6](https://github.com/altmp/altv-issues/assets/1764570/389d172a-032e-4b44-be88-56b4445f81e0)
![GTA5_MLhGnxhq21](https://github.com/altmp/altv-issues/assets/1764570/d2b2b304-bcac-4035-9d16-c3baf79f9504)

**Comment by FabianTerhorst** [comment] 2023-10-23 12:02
Can you post the two position from trailer and truck from the last two images. so the 4 positions? would make fixing it much easier.

**Comment by BluePeer** [comment] 2023-10-23 12:35
[14:32:05] -------------------------------------------------------------------------------
[14:32:05] Player: {"x":1900.00830078125,"y":6344.73681640625,"z":43.30525588989258}
[14:32:05] Truck: {"x":1902.355224609375,"y":6344.38623046875,"z":42.59803009033203}
[14:32:05] Trailer: {"x":1907.6043701171875,"y":6341.630859375,"z":42.79345703125}
[14:32:05] Trailer.isSpawned: true

[14:32:05] -------------------------------------------------------------------------------
[14:32:05] Player: {"x":1899.999267578125,"y":6344.74169921875,"z":43.30051040649414}
[14:32:05] Truck: {"x":1902.3485107421875,"y":6344.39013671875,"z":42.60140609741211}
[14:32:05] Trailer: {"x":1907.695556640625,"y":6341.58984375,"z":42.828182220458984}
[14:32:05] Trailer.isSpawned: false

this is client side "Flash Point" a Captures micro in/out on the line (intervall 0)
the first is the Positions of get VIsible, the bottom is the point of Gone

**Comment by BluePeer** [comment] 2023-10-23 12:40
https://youtu.be/p_HJHfXZMxY
short video with the console output values
[14:37:42] Player: {"x":1900.0205078125,"y":6344.73046875,"z":43.30426788330078}
[14:37:42] Truck: {"x":1902.36767578125,"y":6344.37939453125,"z":42.59809875488281}
[14:37:42] Trailer: {"x":1907.6834716796875,"y":6341.59130859375,"z":42.8271484375}
[14:37:42] Trailer.isSpawned: true

[14:37:49] -------------------------------------------------------------------------------
[14:37:49] Player: {"x":1900.00732421875,"y":6344.736328125,"z":43.30004119873047}
[14:37:49] Truck: {"x":1902.3536376953125,"y":6344.3857421875,"z":42.59077835083008}
[14:37:49] Trailer: {"x":1907.69873046875,"y":6341.57666015625,"z":42.80997085571289}
[14:37:49] Trailer.isSpawned: false

[14:37:56] -------------------------------------------------------------------------------
[14:37:56] Player: {"x":1900.0147705078125,"y":6344.732421875,"z":43.30158996582031}
[14:37:56] Truck: {"x":1902.3621826171875,"y":6344.38134765625,"z":42.59626007080078}
[14:37:56] Trailer: {"x":1907.6834716796875,"y":6341.56494140625,"z":42.79345703125}
[14:37:56] Trailer.isSpawned: true

[14:38:01] -------------------------------------------------------------------------------
[14:38:01] Player: {"x":1900.0086669921875,"y":6344.736328125,"z":43.29985427856445}
[14:38:01] Truck: {"x":1902.3548583984375,"y":6344.384765625,"z":42.590877532958984}
[14:38:01] Trailer: {"x":1907.6944580078125,"y":6341.5654296875,"z":42.809417724609375}
[14:38:01] Trailer.isSpawned: false

**Comment by FabianTerhorst** [comment] 2023-10-25 07:27
Fixed with latest dev build.

**Closed by FabianTerhorst** 2023-10-25 07:27 UTC
Labels: Class: bug
