### ISSUE TITLE
Cursor offset on WebView

### ISSUE THREAD

**Issue by babatonga** [altmp/altv-issues#1683] opened 2022-11-10 01:37 UTC
### Description of the problem

On a WebView with custom set Vector2's for position and size, the cursor has an offset.
I need a custom position and size because the WebView (inside the tablet-frame) is a website on an external webserver.

### Reproduction steps

1. Create a WebView with (url: string, pos: shared.IVector2, size: shared.IVector2)
2. Set focus() on WebView
3. Enable Cursor
4. Try to click a button or link

### Expected behaviour

Cursor should take the offset from WebView into account.

### Additional context

![cursor](https://user-images.githubusercontent.com/3681763/200976084-d2d07d89-4f3d-4a24-b526-0147e1a0fec1.gif)

### Operating system

Windows 11

### Version

release/12.22 (also tested on dev/13.0-dev52)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by zziger** [comment] 2022-11-10 11:04
Duplicate of #1435

**Closed by zziger** 2022-11-10 11:04 UTC
Labels: Class: bug

**Comment by zziger** [comment] 2022-11-10 11:06
Currently for tablet I'd recommend you to try using iframe inside the fullscreen WebView

**Comment by babatonga** [comment] 2022-11-10 18:51
> Currently for tablet I'd recommend you to try using iframe inside the fullscreen WebView

Thank you, that worked! It's been a long time since I've used iframes, thats why I didn't think about them.
