### ISSUE TITLE
vehicle rotation change when a vehicle is created for a client

### ISSUE THREAD

**Issue by so-lar** [altmp/altv-issues#587] opened 2020-07-13 10:51 UTC
If a player streams in a vehicle (and become the network owner?) the vehicle sometimes rotate by a fixed value of +-0.89524 degrees. This only happens, when the vehicle has no driver/passenger. 

Environment:
- release branch
- windows server
- only csharp-module enabled

**Expected behavior**
The vehicles should stay in the last position.

**Current behavior**
You can see the current behavior in the following video: [https://streamable.com/wc3gmq](https://streamable.com/wc3gmq)

Which results in a rotation of the last 3 vehicles like this: [https://cdn.discordapp.com/attachments/731186143256903771/731225968924164107/unknown.png](https://cdn.discordapp.com/attachments/731186143256903771/731225968924164107/unknown.png)

**Steps to reproduce**
example code from the video to reproduce in c#: 

First of all I spawn vehicles on server startup like this: 
```
var veh = Alt.CreateVehicle(dbVehicle.Model, position, rotation) as IGameVehicle;
veh.CorrectRotation = rotation; //store the initial rotation in vehicle entity
```

Then I call the following method, when a vehicle is being created for a client:

```
alt.on('gameEntityCreate', (entity: alt.Entity) => {
    if (entity instanceof alt.Vehicle) {
        alt.emitServer('requestEntityHeading', entity)
    }
})
```

This methods checks the current rotation and the stored rotation on server like this:
```
[AsyncClientEvent("requestEntityHeading")]
public async Task RequestEntityHeadingAsync(IGamePlayer player, IGameVehicle vehicle)
{
	lock (vehicle)
	{
		if (!vehicle.Exists) return;
		
		player.SendLogMessage("current rotation = " + vehicle.Rotation);
		player.SendLogMessage("stored rotation = " + vehicle.CorrectRotation);

		var savedDegree = vehicle.CorrectRotation.Yaw * 180 / Math.PI;
		var currentDegree = vehicle.Rotation.Yaw * 180 / Math.PI;

		var difference = currentDegree - savedDegree;

		player.SendLogMessage("difference in degrees = " + difference);
	}
}
```

_**@Lhoerion will add a js example later to this issue.**_

**Context (environment)**
We run a server with 300+ players. So obv it happens very often, that players streams in a vehicle. Sometimes vehicles rotates by 90+ degrees over a day, which can result into vehicle stucking in walls or vehicles damaging each other and so on. Here is a example: [https://image.prntscr.com/image/eCvALckORjCwONntLyRmgg.png](https://image.prntscr.com/image/eCvALckORjCwONntLyRmgg.png)

**Comment by FabianTerhorst** [comment] 2020-07-13 11:04
Looks same as #585, but won't close because of the reproduction steps.

**Comment by martonp96** [comment] 2020-12-06 11:55
This is fixed in dev branch.

**Comment by LeonMrBonnie** [comment] 2020-12-26 23:26
Confirmed on 2.2-rc15.

**Comment by so-lar** [comment] 2020-12-29 15:45
Hey guys, I just created a simple resource to reproduce the issue described above: [https://cloud.xyx.solar/s/HLWj5MeAKGGmDSB](https://cloud.xyx.solar/s/HLWj5MeAKGGmDSB
)

Steps to reproduce:
1. connect
2. type /tp in chat and wait 6 seconds
3. look in server console (it shows the rotation difference in degrees)

**Comment by DurtyFree** [comment] 2021-04-14 11:14
Adding this for reference: https://www.youtube.com/watch?v=ppgxEeqrYdI

**Comment by FabianTerhorst** [comment] 2021-06-08 21:17
Fxied with dev/4.0-dev12

**Closed by FabianTerhorst** 2021-06-08 21:17 UTC
Labels: Class: bug, Priority: high, Scope: internal, Side: server, Status: confirmed, Status: fix-pending

**Comment by Doxoh** [comment] 2021-06-09 13:27
hey @FabianTerhorst ,

I tested the rotationbug.zip from @so-lar with the new Version "[15:23:15] alt:V Server 4.0-dev12 (dev)"

But the fix does not worked.

Vehicle by spawn: https://gyazo.com/24391ffb0c849c34e9b1701741b60a65
Vehcile after some teleports: https://gyazo.com/5a516cb34e18f099f38250c3831ec553

And the logged rotation degrees after 3 teleports:
dif = 0
dif = 0

dif = -0.01333252925986983
dif = -0.0013113963206450308

dif = 0.015982642657832002
dif = -0.01333252925986983

dif = -0.0019124529676020074
dif = 0.015217661470785515

**Comment by FabianTerhorst** [comment] 2021-06-12 09:18
The vehicle position changes aren't related to this issue and were there before as well.
