### ISSUE TITLE
CheckPoint Color set not working

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#1907] opened 2023-07-13 17:13 UTC
### Description of the problem

Created checkpoint is not visible after rework.

### Reproduction steps

C# Serverside
ICheckpoint Cp = Alt.CreateCheckpoint(47, new Position(0,0,71), 0.7f, 0.7f, new Rgba(0, 200, 255, 150), 20);

### Expected behaviour

Color to be visible

### Operating system

Win11 and Ubuntu 20.04

### Version

15.0-dev351 (dev)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment] 2023-07-13 17:14
Duplicate of #83. Without streaming no setter works.

**Closed by FabianTerhorst** 2023-07-13 17:14 UTC
Labels: Class: bug

**Comment by TuK4z** [comment] 2023-07-13 17:41
Can't find a way to not set StreamingDistance, after rework you have to declare it. Tried 0, that's not working as well

**Comment by FabianTerhorst** [comment] 2023-07-13 17:43
You can only use them clientside
