### ISSUE TITLE
Make LocalStorage instance methods as static methods too

### ISSUE THREAD

**Issue by ZackaryH8** [altmp/altv-issues#822] opened 2021-01-26 19:32 UTC
**Client/server version**
Client: Latest Release
Server: 2.8 - Release

**Current behavior**
```js
alt.LocalStorage.set('data', data)
```
This will return `alt.LocalStorage.set is not a function`

**Expected behavior**
It should save the data using the provided key value pair

**Steps to reproduce**
Use code above

**Context (environment)**
N/A

**Possible solution**
Make local storage instance methods as static methods too

**Comment by mrgharabaghi** [comment] 2021-01-26 23:00
Hello @ZackaryH8
This is not a bug. You have to use this class in propper way.
```js
let myLocal = new alt.LocalStorage;
myLocal.set('myKey', data);
myLocal.save();
```

**Comment by ZackaryH8** [comment] 2021-01-26 23:12
I never said it was a bug, merely suggesting that it be changes to work like browser LocalStorage. The documentation also makes no mention that you must get before running any other methods. Just to be clear you don't need to use `new` keyword, but simply: 
```js
let storage = alt.LocalStorage.get();
storage.set('remember', data);
storage.save();
```

**Comment by LeonMrBonnie** [comment] 2021-05-12 22:14
The local storage methods are now static, and the instance methods are marked as deprecated in newest dev

**Closed by LeonMrBonnie** 2021-05-12 22:14 UTC
Labels: Class: enhancement, Scope: module-api, Side: client
