### ISSUE TITLE
Virtual max players

### ISSUE THREAD

**Issue by yannbcf** [altmp/altv-issues#1819] opened 2023-04-24 09:49 UTC
### Description of the problem

If you use the connectionQueue with a players count of 100 and you want to reserve 15 slots for the server staff, or any person having some priority rights, you will block the server entry at 85/100 players, which can be either frustrating or lead to confusion

### Desired solution for the problem

Add a virtualPlayers config, so you set players to 125 and virtualPlayers to 100, this way the UI shows the virtual value while you can handle the priority logic within the connection queue process

**Comment by FabianTerhorst** [comment] 2023-04-24 09:53
duplicate of #1368

**Closed by FabianTerhorst** 2023-04-24 09:53 UTC
Labels: Class: enhancement
