### ISSUE TITLE
Custom minimap does not work correctly

### ISSUE THREAD

**Issue by NeekoGta** [altmp/altv-issues#961] opened 2021-06-10 08:39 UTC
**Client/server version**

`Build #2.24, branch release`

**Current behavior**

The display of the custom map (ESC) / minimap is not correct. (Explanations and links below)
In ESC menu, is bugged, and in minimap, we see nothing.

![no_minimap_bug_esc_map](https://user-images.githubusercontent.com/70320232/121493012-b19dea00-c9d7-11eb-922e-962932cf271c.jpg)

**Expected behavior**

We should get something similar to 

![8c5896-21 (1)](https://user-images.githubusercontent.com/70320232/121484421-7dbec680-c9cf-11eb-9ede-d9ad7b386538.jpg)

![8c5896-22 14 37 04](https://user-images.githubusercontent.com/70320232/121484426-7e575d00-c9cf-11eb-8c6a-0e9f97bdbcfe.jpg)

**Steps to reproduce**

1. I installed the following map : https://de.gta5-mods.com/maps/las-venturas-san-fierro-dlc-remastered
**This works perfectly**.
2. I installed the Atlas Map (required for SF + LV map) : https://www.gta5-mods.com/misc/atlas-colored-map-16k-that-also-works-in-radar
3. I installed the minimap for SF + LV : https://www.gta5-mods.com/misc/atlas-gta-5-style-map-with-radar-for-las-venturas-san-fierro
3. Gets the `mapzoomdata.meta` and set with MapZoomData API.

Resources : https://mega.nz/file/cE4hAQ4T#Ll1sSBvOjGvnLQD7k-m6Rk_8jj10_QO-JZ3WSEXieC8

**Possible solution**

From the person who created this minimap, it looks like it came from the `minimap.ymt` file which is not streamed by alt:V.
That file will fix the position, size, radar blur, etc.

From Heron, about the `.ymt` file streamed or not, he said me ( :

> hi, yes they are
use the clothes tool

What does that mean ? I don't need to make clothes or to uses this tool to make something with the `.ymt` file 😅

It's been few days that I try to find a solution, discord, DMs ... Without success.µ
Hoping for clarification, thank you very much 😃

**Comment by martonp96** [comment] 2021-06-10 09:07
FYI: Files that required to be streamed when the game starts will not work when you are loading them when the game is already loaded.
Also if you didn't mention what file you want to stream, Heron probably thought you want to stream clothes since that is the most common type.

**Comment by NeekoGta** [comment] 2021-06-10 09:15
Hi @martonp96, thank you for your replay.
About Heron, I specified that it was a file named `minimap.ymt`. But yes, I surely should have provided more details.

About `Files that required to be streamed when the game starts will not work when you are loading them when the game is already loaded.`

What does this mean ? How should I stream the files then ?
I start the server and then the game.

**Comment by FabianTerhorst** [comment] 2021-06-10 10:21
It means streaming the minimap.ymt won't work for now with the current asset loading.

**Comment by LeonMrBonnie** [comment] 2021-07-05 22:04
Duplicate of #956

**Closed by LeonMrBonnie** 2021-07-05 22:04 UTC
Labels: Class: bug, Scope: native, Side: client, Status: confirmed
