### ISSUE TITLE
Rockstar Editor export not working

### ISSUE THREAD

**Issue by devpanda0** [altmp/altv-issues#2101] opened 2023-10-28 14:13 UTC
### Description of the problem

The problem is that you can't export anything in the Rockstart Editor. You can get into the Rockstar Editor and do everything, including exporting. It just does not happen when you press the export button.

### Reproduction steps

First Trigger Recording with F7 then when finish go in Rockstar Editor with F10
Create a new project -> Add clip -> When added back to the project menu -> Export -> Export and then nothing happens. If the project is not yet saved, it should now ask you for the name of the project and then start the export.
clientside
`alt.Events.onKeyDown(async ( { key } ) => {
			if (key === alt.Enums.KeyCode.F7) {
				alt.log('F7 pressed')
				natives.startReplayRecording(1)
				setTimeout(() => {
                                        natives.stopReplayRecording()
			                alt.log('Recording stopped')
				}, 10000)
			}
			if (key === alt.Enums.KeyCode.F10) {
				natives.networkSessionLeaveSinglePlayer()
				natives.activateRockstarEditor(0)
			}
		})`

### Expected behaviour

That it asks me for the project name when the project is not yet saved and then starts the export process. 

### Operating system

Windows 11

### Version

15.0-dev835

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by LeonMrBonnie** [comment] 2023-10-28 14:15
Duplicate of #1880 
(You can save the clips in alt:V, but you have to edit and export them in singleplayer / GTA Online)

**Closed by LeonMrBonnie** 2023-10-28 14:15 UTC
Labels: Class: bug

**Comment by devpanda0** [comment] 2023-10-28 14:20
> (You can save the clips in alt:V, but you have to edit and export them in singleplayer / GTA Online)
yes that goes but then the clothes from the server is no longer loaded and then looks at the character randomly

**Comment by stroopwafel1337** [comment] 2023-10-28 16:26
if you have modded cars, clothes and mlos you need to mod them into singleplayer to be inside the recording

**Comment by devpanda0** [comment] 2023-10-28 16:30
> if you have modded cars, clothes and mlos you need to mod them into singleplayer to be inside the recording

Yes, I know that. But then I don't need a server anymore and that's the point of the thing

**Comment by stroopwafel1337** [comment] 2023-10-28 16:37
> > if you have modded cars, clothes and mlos you need to mod them into singleplayer to be inside the recording
> 
> Yes, I know that. But then I don't need a server anymore and that's the point of the thing

if you want the players to have the proper modded clothing in the recordings then they need to have them aswell. Make a modpack that combines your server mods. But its risky. Thats why nobody uses this feature.

**Comment by devpanda0** [comment] 2023-10-28 16:43
> > > if you have modded cars, clothes and mlos you need to mod them into singleplayer to be inside the recording
> > 
> > 
> > Yes, I know that. But then I don't need a server anymore and that's the point of the thing
> 
> if you want the players to have the proper modded clothing in the recordings then they need to have them aswell. Make a modpack that combines your server mods. But its risky. Thats why nobody uses this feature.

It does not have to be active by default, the function. The server owner could say via Config whether he allows the export and he must also first install the clip function with the natives.

**Comment by devpanda0** [comment] 2023-10-28 17:08
I am for example working on a Menyoo project where this export is needed to make a rolling shot. Where also must say the export is only a mp4 file more not. Since now see no problems
